"""Input and output helpers."""

from schwgw.io.apparent import (
    ApparentGridResult,
    load_apparent_results,
    run_apparent_solver_grid,
    save_apparent_results,
)
from schwgw.io.asymptotic import (
    FIG8_KM_VALUES,
    FIG8_REDUCTION_ORDERS,
    Fig8AsymptoticDataset,
    build_fig8_matched_dataset,
    default_fig8_theta_grid,
    load_fig8_asymptotic_dataset,
    produce_fig8_asymptotic_dataset,
    save_fig8_asymptotic_dataset,
)

from schwgw.io.config import (
    BackgroundConfig,
    BoundarySettings,
    ConvergenceConfig,
    ConfigError,
    NumericsConfig,
    ObserverConfig,
    SolverConfig,
    WaveConfig,
    load_config,
    parse_config,
)
from schwgw.io.results import (
    AmplificationGridResult,
    GridResult,
    ResultFormatError,
    load_amplification_results,
    load_results,
    run_solver_grid,
    save_amplification_results,
    save_results,
)
from schwgw.io.kirchhoff import generate_kirchhoff_review_grid_artifact
from schwgw.io.tablei import (
    TABLEI_POINTS,
    TableIPoint,
    builtin_tablei_points,
    extract_tablei_four_frequency_from_amplification_results,
)
from schwgw.io.tablei_risk_pilot import (
    PILOT_FREQUENCIES,
    PILOT_LMAX_VALUES,
    PilotContractError,
    run_delta0p1_risk_pilot,
)
from schwgw.io.tablei_uniform import (
    MISSING_FREQUENCIES,
    UNIFORM_FREQUENCIES,
    UNIFORM_LMAX_VALUES,
    UniformContractError,
    merge_tablei_uniform,
    preflight_tablei_uniform,
    run_tablei_uniform_missing,
)
from schwgw.io.tablei_adaptive_refinement import (
    ADAPTIVE_FREQUENCIES,
    ADAPTIVE_LMAX_VALUES,
    AdaptiveRefinementContractError,
    run_targeted_adaptive_refinement,
)
from schwgw.io.tablei_further_local_refinement import (
    FURTHER_LOCAL_FREQUENCIES,
    FURTHER_LOCAL_LMAX_VALUES,
    FurtherLocalRefinementContractError,
    run_further_local_refinement,
)
from schwgw.io.tablei_literal_failed_child_refinement import (
    LITERAL_FAILED_CHILD_FREQUENCIES,
    LITERAL_FAILED_CHILD_LMAX_VALUES,
    LiteralFailedChildRefinementContractError,
    run_literal_failed_child_refinement,
)
from schwgw.io.tablei_another_bounded_local_refinement import (
    ANOTHER_BOUNDED_LOCAL_FREQUENCIES,
    ANOTHER_BOUNDED_LOCAL_LMAX_VALUES,
    AnotherBoundedLocalRefinementContractError,
    run_another_bounded_local_refinement,
)

__all__ = [
    "ApparentGridResult",
    "FIG8_KM_VALUES",
    "FIG8_REDUCTION_ORDERS",
    "Fig8AsymptoticDataset",
    "build_fig8_matched_dataset",
    "BackgroundConfig",
    "BoundarySettings",
    "ConvergenceConfig",
    "ConfigError",
    "GridResult",
    "AmplificationGridResult",
    "ADAPTIVE_FREQUENCIES",
    "ADAPTIVE_LMAX_VALUES",
    "AdaptiveRefinementContractError",
    "FURTHER_LOCAL_FREQUENCIES",
    "FURTHER_LOCAL_LMAX_VALUES",
    "FurtherLocalRefinementContractError",
    "LITERAL_FAILED_CHILD_FREQUENCIES",
    "LITERAL_FAILED_CHILD_LMAX_VALUES",
    "LiteralFailedChildRefinementContractError",
    "ANOTHER_BOUNDED_LOCAL_FREQUENCIES",
    "ANOTHER_BOUNDED_LOCAL_LMAX_VALUES",
    "AnotherBoundedLocalRefinementContractError",
    "NumericsConfig",
    "ObserverConfig",
    "PILOT_FREQUENCIES",
    "PILOT_LMAX_VALUES",
    "PilotContractError",
    "ResultFormatError",
    "SolverConfig",
    "TABLEI_POINTS",
    "TableIPoint",
    "WaveConfig",
    "builtin_tablei_points",
    "extract_tablei_four_frequency_from_amplification_results",
    "generate_kirchhoff_review_grid_artifact",
    "load_config",
    "load_fig8_asymptotic_dataset",
    "load_amplification_results",
    "load_apparent_results",
    "load_results",
    "parse_config",
    "default_fig8_theta_grid",
    "produce_fig8_asymptotic_dataset",
    "run_solver_grid",
    "run_apparent_solver_grid",
    "save_amplification_results",
    "save_apparent_results",
    "save_fig8_asymptotic_dataset",
    "save_results",
    "run_delta0p1_risk_pilot",
    "MISSING_FREQUENCIES",
    "UNIFORM_FREQUENCIES",
    "UNIFORM_LMAX_VALUES",
    "UniformContractError",
    "merge_tablei_uniform",
    "preflight_tablei_uniform",
    "run_tablei_uniform_missing",
    "run_targeted_adaptive_refinement",
    "run_further_local_refinement",
    "run_literal_failed_child_refinement",
    "run_another_bounded_local_refinement",
]
