"""Partial-wave assembly and observable extraction."""

from schwgw.scattering.apparent import (
    ApparentPolarizationResult,
    apparent_polarization_acceleration_from_strict_np,
    apparent_polarizations_from_strict_np,
)
from schwgw.scattering.asymptotic import (
    HybridPhaseSeries,
    ParityScatteringSeries,
    ReducedLegendreSeries,
    ScatteringMatrixResult,
    evaluate_reduced_legendre_series,
    matched_schwarzschild_phase_factors,
    outer_matching_phase_corrected,
    parity_scattering_series,
    poisson_sasaki_odd_phase_factor,
    reduce_legendre_series,
    reduce_truncated_legendre_series,
    scattering_matrix_cross_section,
    schwarzschild_even_from_odd,
)
from schwgw.scattering.kirchhoff import (
    KirchhoffEq47Result,
    compute_kirchhoff_eq47,
)
from schwgw.scattering.tetrads import (
    NullTetrad,
    incident_cartesian_tetrad,
    kinnersley_tetrad,
    tetrad_inner_product,
    tetrad_inner_products,
)
from schwgw.scattering.observables import (
    ElectricTidalComponents,
    PackagedPolarizationScalars,
    PolarizationResult,
    package_electric_tidal_components,
    packaged_scalars_to_mapping,
    polarization_acceleration_from_packaged_scalars,
    polarization_acceleration_from_weyl,
    polarization_from_packaged_scalars,
    polarization_from_weyl,
)
from schwgw.scattering.partial_wave import (
    compute_apparent_polarizations,
    compute_flat_no_lens_polarization,
    compute_flat_no_lens_partial_wave_diagnostic,
    compute_flat_no_lens_partial_wave_strict_np_weyl,
    compute_polarization,
    direct_cartesian_tt_packaged_weyl,
    direct_cartesian_tt_polarization,
    direct_cartesian_tt_strict_np_weyl,
    direct_cartesian_tt_weyl,
    flat_no_lens_expected_polarization,
)
from schwgw.scattering.transmission import (
    PointwiseAmplificationResult,
    compute_pointwise_amplification,
    flat_no_lens_baseline_at_point,
)
from schwgw.scattering.weyl import (
    StrictNPScalars,
    WeylModeComponents,
    assemble_weyl_scalars,
    compute_packaged_polarization_scalars,
    transform_strict_np_weyl_to_incident_tetrad,
    transform_weyl_to_incident_tetrad,
    weyl_mode_components,
)

__all__ = [
    "ApparentPolarizationResult",
    "ElectricTidalComponents",
    "HybridPhaseSeries",
    "KirchhoffEq47Result",
    "NullTetrad",
    "PackagedPolarizationScalars",
    "ParityScatteringSeries",
    "PointwiseAmplificationResult",
    "PolarizationResult",
    "ReducedLegendreSeries",
    "ScatteringMatrixResult",
    "StrictNPScalars",
    "WeylModeComponents",
    "assemble_weyl_scalars",
    "apparent_polarization_acceleration_from_strict_np",
    "apparent_polarizations_from_strict_np",
    "compute_flat_no_lens_polarization",
    "compute_apparent_polarizations",
    "compute_flat_no_lens_partial_wave_diagnostic",
    "compute_flat_no_lens_partial_wave_strict_np_weyl",
    "compute_packaged_polarization_scalars",
    "compute_kirchhoff_eq47",
    "compute_polarization",
    "compute_pointwise_amplification",
    "direct_cartesian_tt_packaged_weyl",
    "direct_cartesian_tt_polarization",
    "direct_cartesian_tt_strict_np_weyl",
    "direct_cartesian_tt_weyl",
    "evaluate_reduced_legendre_series",
    "flat_no_lens_expected_polarization",
    "flat_no_lens_baseline_at_point",
    "incident_cartesian_tetrad",
    "kinnersley_tetrad",
    "matched_schwarzschild_phase_factors",
    "outer_matching_phase_corrected",
    "package_electric_tidal_components",
    "parity_scattering_series",
    "poisson_sasaki_odd_phase_factor",
    "packaged_scalars_to_mapping",
    "polarization_acceleration_from_packaged_scalars",
    "polarization_acceleration_from_weyl",
    "polarization_from_packaged_scalars",
    "polarization_from_weyl",
    "reduce_legendre_series",
    "reduce_truncated_legendre_series",
    "scattering_matrix_cross_section",
    "schwarzschild_even_from_odd",
    "tetrad_inner_product",
    "tetrad_inner_products",
    "transform_strict_np_weyl_to_incident_tetrad",
    "transform_weyl_to_incident_tetrad",
    "weyl_mode_components",
]
