"""Direct numerical Schwarzschild MST scattering phase factors.

The implementation follows the three-term Mano--Suzuki--Takasugi recurrence
and connection-coefficient formulas in Mano, Suzuki & Takasugi (1996), with
the numerical organization cross-checked against Jovan Tan's MIT-licensed
``NumericalMST.nb`` (commit ``354d3d70e439f1c8bb721cb4e9ea6562541110a8``).

Only the Schwarzschild gravitational case required by Fig. 8 is exposed:
``q=0``, Teukolsky recurrence spin ``s=-2``, and ``epsilon=2 M k``.
No empirical overlap offset or blending enters this module.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Callable

import numpy as np

try:
    import mpmath as mp
except ModuleNotFoundError:  # pragma: no cover - exercised in minimal installs
    class _MissingMpmath:
        def __getattr__(self, name: str) -> object:
            del name
            raise ModuleNotFoundError(
                "direct MST phases require the optional 'oracle' dependency "
                "(install schw-gw-waveoptics[oracle])"
            )

    mp = _MissingMpmath()  # type: ignore[assignment]


@dataclass(frozen=True)
class MSTPhaseFactor:
    ell: int
    epsilon: float
    nu: complex
    odd: complex
    even: complex
    recurrence_residual: float
    truncation: int
    guard_terms: int
    working_dps: int


def schwarzschild_mst_phase_factor(
    ell: int,
    *,
    k: float,
    M: float = 1.0,
    truncation: int = 30,
    guard_terms: int = 24,
    working_dps: int = 70,
) -> MSTPhaseFactor:
    """Return direct odd/even gravitational MST phase factors.

    ``odd`` and ``even`` are ``exp(2 i delta_l^-)`` and
    ``exp(2 i delta_l^+)`` respectively.  The parity ratio is generated by
    the Starobinsky constant inside the MST formula, not imposed afterwards.
    """

    if not isinstance(ell, int) or isinstance(ell, bool) or ell < 2:
        raise ValueError("ell must be an integer >= 2")
    if not math.isfinite(k) or k <= 0.0 or not math.isfinite(M) or M <= 0.0:
        raise ValueError("k and M must be finite and positive")
    if truncation < 8 or guard_terms < 4 or working_dps < 40:
        raise ValueError("MST truncation/guard/precision is too small")
    epsilon = 2.0 * float(M) * float(k)
    with mp.workdps(working_dps):
        eps = mp.mpf(epsilon)
        nu = _renormalized_angular_momentum(
            ell=ell,
            epsilon=eps,
            depth=truncation + guard_terms,
        )
        alpha, beta, gamma = _recurrence_functions(
            ell=ell,
            epsilon=eps,
            nu=nu,
        )
        coefficients = _mst_coefficients(
            alpha=alpha,
            beta=beta,
            gamma=gamma,
            truncation=truncation,
            guard_terms=guard_terms,
        )
        common = _reflection_over_incident(
            ell=ell,
            epsilon=eps,
            nu=nu,
            coefficients=coefficients,
            truncation=truncation,
        )
        sigma = mp.mpf((ell - 1) * ell * (ell + 1) * (ell + 2))
        odd = ((-1) ** (ell + 1)) * (sigma - 6j * eps) * common / eps**4
        even = ((-1) ** (ell + 1)) * (sigma + 6j * eps) * common / eps**4
        residual = abs(beta(0) + alpha(0) * coefficients[1] + gamma(0) * coefficients[-1])
        values = (complex(nu), complex(odd), complex(even))
    if not all(math.isfinite(v.real) and math.isfinite(v.imag) for v in values):
        raise RuntimeError("MST phase calculation produced a non-finite value")
    return MSTPhaseFactor(
        ell=ell,
        epsilon=epsilon,
        nu=values[0],
        odd=values[1],
        even=values[2],
        recurrence_residual=float(residual),
        truncation=truncation,
        guard_terms=guard_terms,
        working_dps=working_dps,
    )


def schwarzschild_mst_phase_series(
    ell: np.ndarray,
    *,
    k: float,
    M: float = 1.0,
    truncation: int = 30,
    guard_terms: int = 24,
    working_dps: int = 70,
) -> tuple[np.ndarray, np.ndarray, list[MSTPhaseFactor]]:
    """Evaluate a direct, unblended MST phase-factor sequence."""

    ell_values = np.asarray(ell)
    if ell_values.ndim != 1 or ell_values.size == 0:
        raise ValueError("ell must be a non-empty vector")
    if not np.issubdtype(ell_values.dtype, np.integer) or np.any(ell_values < 2):
        raise ValueError("ell must contain integers >= 2")
    records = [
        schwarzschild_mst_phase_factor(
            int(value),
            k=k,
            M=M,
            truncation=truncation,
            guard_terms=guard_terms,
            working_dps=working_dps,
        )
        for value in ell_values
    ]
    odd = np.asarray([record.odd for record in records], dtype=np.complex128)
    even = np.asarray([record.even for record in records], dtype=np.complex128)
    return odd, even, records


def _recurrence_functions(
    *,
    ell: int,
    epsilon: mp.mpf,
    nu: mp.mpf | mp.mpc,
) -> tuple[Callable[[int], mp.mpc], Callable[[int], mp.mpc], Callable[[int], mp.mpc]]:
    spin = mp.mpf(-2)
    eigenvalue = mp.mpf(ell * (ell + 1) - 2)

    def alpha(index: int) -> mp.mpc:
        value = mp.mpf(index) + nu
        return (
            1j
            * epsilon
            * (value + 1 + spin + 1j * epsilon)
            * (value + 1 + spin - 1j * epsilon)
            * (value + 1 + 1j * epsilon)
            / ((value + 1) * (2 * value + 3))
        )

    def beta(index: int) -> mp.mpc:
        value = mp.mpf(index) + nu
        return (
            -eigenvalue
            - spin * (spin + 1)
            + value * (value + 1)
            + 2 * epsilon**2
            + epsilon**2 * (spin**2 + epsilon**2) / (value * (value + 1))
        )

    def gamma(index: int) -> mp.mpc:
        value = mp.mpf(index) + nu
        return (
            -1j
            * epsilon
            * (value - spin + 1j * epsilon)
            * (value - spin - 1j * epsilon)
            * (value - 1j * epsilon)
            / (value * (2 * value - 1))
        )

    return alpha, beta, gamma


def _continued_fraction_residual(
    nu: mp.mpf,
    *,
    ell: int,
    epsilon: mp.mpf,
    depth: int,
) -> mp.mpf:
    alpha, beta, gamma = _recurrence_functions(
        ell=ell,
        epsilon=epsilon,
        nu=nu,
    )
    right = -gamma(depth) / beta(depth)
    for index in range(depth - 1, 0, -1):
        right = -gamma(index) / (beta(index) + alpha(index) * right)
    left = -alpha(-depth) / beta(-depth)
    for index in range(-depth + 1, 0):
        left = -alpha(index) / (beta(index) + gamma(index) * left)
    value = beta(0) + alpha(0) * right + gamma(0) * left
    if abs(mp.im(value)) > mp.mpf("1e-30") * max(1, abs(value)):
        raise RuntimeError("Schwarzschild MST real-nu residual acquired an imaginary part")
    return mp.re(value)


def _renormalized_angular_momentum(
    *, ell: int, epsilon: mp.mpf, depth: int
) -> mp.mpf:
    def residual(value: mp.mpf) -> mp.mpf:
        return _continued_fraction_residual(
            value,
            ell=ell,
            epsilon=epsilon,
            depth=depth,
        )

    left = mp.mpf(ell) - mp.mpf("0.499")
    right = mp.mpf(ell) + mp.mpf("0.499")
    grid = [left + (right - left) * index / 160 for index in range(161)]
    candidates: list[tuple[mp.mpf, mp.mpf]] = []
    previous_x: mp.mpf | None = None
    previous_y: mp.mpf | None = None
    for current_x in grid:
        try:
            current_y = residual(current_x)
        except ZeroDivisionError:
            previous_x = previous_y = None
            continue
        if previous_x is not None and previous_y is not None:
            if previous_y == 0 or current_y == 0 or previous_y * current_y < 0:
                candidates.append((previous_x, current_x))
        previous_x, previous_y = current_x, current_y
    if not candidates:
        estimate = mp.mpf(ell) - epsilon**2 / (2 * ell + 1)
        root = mp.findroot(residual, (estimate - mp.mpf("0.02"), estimate + mp.mpf("0.02")))
    else:
        root = None
        ordered = sorted(
            candidates,
            key=lambda pair: (
                max(abs(residual(pair[0])), abs(residual(pair[1]))),
                abs((pair[0] + pair[1]) / 2 - ell),
            ),
        )
        for bracket in ordered:
            try:
                candidate = mp.findroot(
                    residual,
                    bracket,
                    solver="bisect",
                    verify=False,
                    maxsteps=240,
                )
                if abs(residual(candidate)) <= mp.mpf("1e-30"):
                    root = candidate
                    break
            except (ValueError, ZeroDivisionError):
                continue
        if root is None:
            raise RuntimeError("MST could not isolate the physical real-nu root")
    if abs(root - ell) >= mp.mpf("0.5"):
        raise RuntimeError("MST selected the wrong renormalized-angular-momentum branch")
    return root


def _mst_coefficients(
    *,
    alpha: Callable[[int], mp.mpc],
    beta: Callable[[int], mp.mpc],
    gamma: Callable[[int], mp.mpc],
    truncation: int,
    guard_terms: int,
) -> dict[int, mp.mpc]:
    top = truncation + guard_terms
    ratios: dict[int, mp.mpc] = {top: -gamma(top) / beta(top)}
    for index in range(top - 1, 0, -1):
        ratios[index] = -gamma(index) / (
            beta(index) + alpha(index) * ratios[index + 1]
        )
    values: dict[int, mp.mpc] = {0: mp.mpc(1), 1: ratios[1]}
    for index in range(2, truncation + 1):
        values[index] = (
            -beta(index - 1) * values[index - 1]
            - gamma(index - 1) * values[index - 2]
        ) / alpha(index - 1)
    for index in range(-1, -truncation - 1, -1):
        values[index] = (
            -beta(index + 1) * values[index + 1]
            - alpha(index + 1) * values[index + 2]
        ) / gamma(index + 1)
    return values


def _connection_coefficient(
    *,
    nu: mp.mpc,
    epsilon: mp.mpf,
    coefficients: dict[int, mp.mpc],
    truncation: int,
) -> mp.mpc:
    spin = mp.mpf(-2)
    prefactor = (
        mp.e ** (1j * epsilon)
        * (2 * epsilon) ** (spin - nu)
        * 2 ** (-spin)
        * mp.gamma(1 - spin - 2j * epsilon)
        * mp.gamma(2 * nu + 2)
        / (
            mp.gamma(nu + 1 - spin + 1j * epsilon)
            * mp.gamma(nu + 1 + 1j * epsilon)
            * mp.gamma(nu + 1 + spin + 1j * epsilon)
        )
    )
    numerator = mp.fsum(
        (-1) ** index
        * mp.gamma(index + 2 * nu + 1)
        / mp.factorial(index)
        * mp.gamma(index + nu + 1 + spin + 1j * epsilon)
        / mp.gamma(index + nu + 1 - spin - 1j * epsilon)
        * mp.gamma(index + nu + 1 + 1j * epsilon)
        / mp.gamma(index + nu + 1 - 1j * epsilon)
        * coefficients[index]
        for index in range(0, truncation + 1)
    )
    denominator = mp.fsum(
        (-1) ** index
        / (mp.factorial(-index) * mp.rf(2 * nu + 2, index))
        * mp.rf(nu + 1 + spin - 1j * epsilon, index)
        / mp.rf(nu + 1 - spin + 1j * epsilon, index)
        * coefficients[index]
        for index in range(-truncation, 1)
    )
    return prefactor * numerator / denominator


def _reflection_over_incident(
    *,
    ell: int,
    epsilon: mp.mpf,
    nu: mp.mpc,
    coefficients: dict[int, mp.mpc],
    truncation: int,
) -> mp.mpc:
    spin = mp.mpf(-2)
    a_plus = (
        mp.e ** (-mp.pi * epsilon / 2)
        * mp.e ** (1j * mp.pi * (nu + 1 - spin) / 2)
        * 2 ** (-1 + spin - 1j * epsilon)
        * mp.gamma(nu + 1 - spin + 1j * epsilon)
        / mp.gamma(nu + 1 + spin - 1j * epsilon)
        * mp.fsum(coefficients[index] for index in range(-truncation, truncation + 1))
    )
    a_minus = (
        2 ** (-1 - spin + 1j * epsilon)
        * mp.e ** (-1j * mp.pi * (nu + 1 + spin) / 2)
        * mp.e ** (-mp.pi * epsilon / 2)
        * mp.fsum(
            (-1) ** index
            * mp.rf(nu + 1 + spin - 1j * epsilon, index)
            / mp.rf(nu + 1 - spin + 1j * epsilon, index)
            * coefficients[index]
            for index in range(-truncation, truncation + 1)
        )
    )
    k_nu = _connection_coefficient(
        nu=nu,
        epsilon=epsilon,
        coefficients=coefficients,
        truncation=truncation,
    )
    reflected_coefficients = {
        index: coefficients[-index] for index in range(-truncation, truncation + 1)
    }
    negative_nu = -nu - 1
    k_negative = _connection_coefficient(
        nu=negative_nu,
        epsilon=epsilon,
        coefficients=reflected_coefficients,
        truncation=truncation,
    )
    connection_ratio = (
        k_nu + 1j * mp.e ** (1j * mp.pi * nu) * k_negative
    ) / (
        k_nu
        - 1j
        * mp.e ** (-1j * mp.pi * nu)
        * mp.sin(mp.pi * (nu - spin + 1j * epsilon))
        / mp.sin(mp.pi * (nu + spin - 1j * epsilon))
        * k_negative
    )
    omega = epsilon / 2
    return (
        omega ** (-2 * spin)
        * mp.e ** (2j * epsilon * mp.log(epsilon))
        * connection_ratio
        * a_minus
        / a_plus
    )


__all__ = [
    "MSTPhaseFactor",
    "schwarzschild_mst_phase_factor",
    "schwarzschild_mst_phase_series",
]
