#!/usr/bin/env python3
"""Run exactly one frozen Phase-6 generic-conditioning shard.

There is intentionally no all-shards option.  A caller must name one of the
86 frozen ``kM/sector`` shards and a fresh output root.  Paper figures are not
read or generated by this runner.
"""

from __future__ import annotations

import argparse
from collections.abc import Callable, Mapping, Sequence
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import platform
import stat
import sys
import time

import numpy as np
import scipy

from schwgw.validation.phase6_conditioning_scan import (
    CHECKPOINT_SCHEMA,
    DEFAULT_POLICY,
    KEY_PAYLOAD_ENVELOPE_SCHEMA,
    KEY_RESULT_SCHEMA,
    KEY_TERMINAL_SCHEMA,
    RUN_CONTRACT_SCHEMA,
    SHARD_FAILURE_SCHEMA,
    SOLVER_PAYLOAD_SCHEMA,
    ConditionedSolver,
    ConditioningPolicy,
    FrozenScanContract,
    OuterSelection,
    calibration_solve_nodes,
    checkpoint_fields_from_solver_payload,
    execute_key_scan,
    key_artifact_filenames,
    load_frozen_scan_contract,
    scan_context_hash,
    select_outer_boundary,
    source_hash_map,
)
from schwgw.validation.phase6_domain import (
    RadialKey,
    canonical_json_bytes,
    sha256_bytes,
    source_file_identity,
)
from schwgw.validation.phase6_execution_contract import (
    CONVENTION_BUDGET_FIELDS,
    NUMERICAL_BUDGET_FIELDS,
    SHARD_CHECKPOINT_SCHEMA,
    SHARD_RESULT_SCHEMA,
    ExecutionContractError,
    resume_claims_sha256,
    validate_key_checkpoint,
    validate_resume_eligible,
)


ROOT = Path(__file__).resolve().parents[1]
DOMAIN_ROOT = ROOT / "runs/phase6/v1_domain_freeze_v3_20260806"
EXECUTION_ROOT = ROOT / "runs/phase6/v1_execution_contract_v4_20260806"
SCAN_SOURCE = ROOT / "src/schwgw/validation/phase6_conditioning_scan.py"
CONDITIONED_SOURCE = ROOT / "src/schwgw/numerics/conditioned_radial.py"
MATCHING_SOURCE = ROOT / "src/schwgw/numerics/matching.py"
POTENTIAL_SOURCE = ROOT / "src/schwgw/perturbations/potentials.py"
BACKGROUND_SOURCE = ROOT / "src/schwgw/backgrounds/schwarzschild.py"
BACKGROUND_BASE_SOURCE = ROOT / "src/schwgw/backgrounds/base.py"


class ShardRunError(RuntimeError):
    """Raised after a shard has published a durable fail-closed root."""


def _fsync_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _publish_json_exclusive(path: Path, payload: object) -> dict[str, object]:
    """Publish complete canonical JSON atomically without replacing a path."""

    if path.exists() or path.is_symlink():
        raise FileExistsError(f"output collision: {path}")
    data = canonical_json_bytes(payload)
    staging = path.with_name(
        f".{path.name}.o_excl_staging_{os.getpid()}_{time.time_ns()}"
    )
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    descriptor = os.open(staging, flags, 0o600)
    linked = False
    try:
        with os.fdopen(descriptor, "wb", closefd=True) as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(staging, 0o444)
        _fsync_directory(path.parent)
        os.link(staging, path, follow_symlinks=False)
        linked = True
        _fsync_directory(path.parent)
    except Exception:
        try:
            os.close(descriptor)
        except OSError:
            pass
        raise
    finally:
        try:
            staging.unlink()
        except FileNotFoundError:
            pass
        _fsync_directory(path.parent)
    if not linked:
        raise RuntimeError("exclusive JSON publication did not create a final link")
    identity = source_file_identity(path)
    if identity["mode"] != 0o444 or identity["sha256"] != sha256_bytes(data):
        raise RuntimeError("exclusive JSON publication identity mismatch")
    return identity


def _strict_json(path: Path) -> dict[str, object]:
    if path.is_symlink() or not path.is_file():
        raise ShardRunError(f"JSON artifact is missing or aliased: {path}")
    raw = path.read_bytes()
    try:
        value = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ShardRunError(f"JSON artifact is malformed: {path}") from exc
    if not isinstance(value, dict) or raw != canonical_json_bytes(value):
        raise ShardRunError(f"JSON artifact is not a canonical object: {path}")
    return value


def _validate_identity(
    identity: object,
    *,
    path: Path,
) -> dict[str, object]:
    if not isinstance(identity, Mapping) or set(identity) != {
        "mode",
        "nlink",
        "path",
        "sha256",
        "size",
    }:
        raise ShardRunError("artifact identity schema changed")
    actual = source_file_identity(path)
    if actual["mode"] != 0o444 or actual != dict(identity):
        raise ShardRunError(f"artifact identity changed: {path}")
    return actual


def _source_identities() -> dict[str, Mapping[str, object]]:
    paths = {
        "background_base": BACKGROUND_BASE_SOURCE,
        "conditioned_backend": CONDITIONED_SOURCE,
        "matching": MATCHING_SOURCE,
        "potentials": POTENTIAL_SOURCE,
        "scan_module": SCAN_SOURCE,
        "schwarzschild_background": BACKGROUND_SOURCE,
        "shard_runner": Path(__file__).resolve(strict=True),
    }
    return {name: source_file_identity(path) for name, path in sorted(paths.items())}


def _runtime_identity() -> dict[str, object]:
    return {
        "actual_arithmetic": {
            "backend": "scipy_float64_conditioned_radial_v1",
            "decimal_digits": 15.95,
            "numpy_dtype": "complex128/float64",
            "precision_bits": 53,
        },
        "numpy": {
            "origin": str(Path(np.__file__).resolve(strict=True)),
            "version": np.__version__,
        },
        "python": {
            "executable": str(Path(sys.executable).resolve(strict=True)),
            "implementation": platform.python_implementation(),
            "version": platform.python_version(),
        },
        "scipy": {
            "origin": str(Path(scipy.__file__).resolve(strict=True)),
            "version": scipy.__version__,
        },
    }


Selector = Callable[[RadialKey], OuterSelection]


def _build_run_contract(
    *,
    frozen: FrozenScanContract,
    shard_id: str,
    output_root: Path,
    resume_from: Path | None,
    policy: ConditioningPolicy,
    selector: Selector,
    test_mode: bool,
    selector_injected: bool,
    solver_injected: bool,
) -> tuple[dict[str, object], dict[RadialKey, OuterSelection]]:
    shard = dict(frozen.shard_record(shard_id))
    keys = frozen.shard_keys(shard_id)
    union_ordinals = {key: index for index, key in enumerate(frozen.union_keys)}
    plans: list[dict[str, object]] = []
    selections: dict[RadialKey, OuterSelection] = {}
    for shard_ordinal, key in enumerate(keys):
        selection = selector(key)
        if selection.key != key:
            raise ShardRunError("selector returned a foreign key")
        selections[key] = selection
        transition_key = key in frozen.transition_keys
        nodes = calibration_solve_nodes(
            selection,
            transition_key=transition_key,
            policy=policy,
        )
        if selection.supported:
            descriptors = [node.descriptor() for node in nodes]
        else:
            descriptors = [
                {
                    "actual_precision_digits": 16,
                    "node_id": "baseline_preflight",
                    "tolerance": policy.baseline_rtol,
                }
            ]
        plans.append(
            {
                "domain_ordinal": union_ordinals[key],
                "key": key.to_record(),
                "ladder_axis_descriptors": descriptors,
                "ladder_axis_map_sha256": sha256_bytes(
                    canonical_json_bytes(descriptors)
                ),
                "outer_selection": selection.to_record(),
                "shard_ordinal": shard_ordinal,
                "solve_nodes": [node.to_record() for node in nodes],
                "transition_key": transition_key,
            }
        )
    sources = _source_identities()
    domain_hashes = {
        f"domain:{name}": identity["sha256"]
        for name, identity in sorted(frozen.domain_identities.items())
    }
    execution_hashes = {
        f"execution:{name}": identity["sha256"]
        for name, identity in sorted(frozen.execution_identities.items())
    }
    implementation_hashes = {
        f"source:{name}": digest for name, digest in source_hash_map(sources).items()
    }
    source_hashes = {**domain_hashes, **execution_hashes, **implementation_hashes}
    record: dict[str, object] = {
        "actual_precision": {
            "backend": "scipy_float64_conditioned_radial_v1",
            "digits": 16,
        },
        "backend_hashes": {
            "conditioned_backend": sources["conditioned_backend"]["sha256"],
            "matching": sources["matching"]["sha256"],
            "potentials": sources["potentials"]["sha256"],
        },
        "code_hashes": {
            "scan_module": sources["scan_module"]["sha256"],
            "shard_runner": sources["shard_runner"]["sha256"],
        },
        "config_hashes": {"conditioning_policy": policy.sha256},
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "domain_contract_sha256": frozen.domain_identities["domain_contract.json"][
            "sha256"
        ],
        "domain_union_key_list_sha256": frozen.domain_identities["D_union.jsonl"][
            "sha256"
        ],
        "execution_contract_sha256": frozen.execution_identities[
            "execution_contract.json"
        ]["sha256"],
        "execution_manifest_sha256": frozen.execution_identities["manifest.json"][
            "sha256"
        ],
        "execution_mode": {
            "scientific_use_permitted": not test_mode,
            "selector_injected": selector_injected,
            "solver_injected": solver_injected,
            "status": (
                "TEST_ONLY_FAKE_INJECTION_NO_SCIENTIFIC_USE"
                if test_mode
                else "PRODUCTION_GENERIC_CONDITIONED_BACKEND"
            ),
        },
        "global_green_permitted": False,
        "key_plans": plans,
        "observable_definitions": {
            "flux_residual": "abs(|A_out|^2 + |T_horizon|^2 - 1)",
            "normalization": "A_in=1 at infinity",
            "production_finite_radius_states": "NOT_ASSESSED",
            "radial_s_matrix": "S_ell=-A_out/(-1)^ell",
            "required_radius_state": f"Schwarzschild radius r/M={policy.required_radius_M:.17g}",
        },
        "output_root": str(output_root),
        "paper_figure_runs": 0,
        "policy": policy.to_record(),
        "policy_sha256": policy.sha256,
        "resume_from": None if resume_from is None else str(resume_from),
        "runtime_identity": _runtime_identity(),
        "schema": RUN_CONTRACT_SCHEMA,
        "shard": shard,
        "shard_keys": [key.to_record() for key in keys],
        "source_hashes": source_hashes,
        "source_identities": sources,
        "status": "FROZEN_SHARD_PLAN_NO_ACCEPTANCE_CLAIM",
        "transition_contract_sha256": frozen.execution_identities[
            "D_transition_calibration.jsonl"
        ]["sha256"],
    }
    record["context_sha256"] = scan_context_hash(record)
    return record, selections


def _expected_key_context(
    contract: Mapping[str, object],
    plan: Mapping[str, object],
    *,
    evidence_root: Path,
) -> dict[str, object]:
    return {
        "actual_precision": contract["actual_precision"],
        "backend_hashes": contract["backend_hashes"],
        "code_hashes": contract["code_hashes"],
        "config_hashes": contract["config_hashes"],
        "domain_contract_sha256": contract["domain_contract_sha256"],
        "domain_union_key_list_sha256": contract["domain_union_key_list_sha256"],
        "evidence_root": str(evidence_root),
        "execution_contract_sha256": contract["execution_contract_sha256"],
        "execution_manifest_sha256": contract["execution_manifest_sha256"],
        "ladder_axis_descriptors": plan["ladder_axis_descriptors"],
        "ladder_axis_map_sha256": plan["ladder_axis_map_sha256"],
        "shard": contract["shard"],
        "shard_keys": contract["shard_keys"],
        "source_hashes": contract["source_hashes"],
    }


def _checkpoint_base(
    *,
    contract: Mapping[str, object],
    solver_payload: Mapping[str, object],
) -> dict[str, object]:
    projected = checkpoint_fields_from_solver_payload(solver_payload)
    return {
        **projected,
        "backend_hashes": contract["backend_hashes"],
        "code_hashes": contract["code_hashes"],
        "config_hashes": contract["config_hashes"],
        "domain_contract_sha256": contract["domain_contract_sha256"],
        "domain_union_key_list_sha256": contract["domain_union_key_list_sha256"],
        "execution_contract_sha256": contract["execution_contract_sha256"],
        "execution_manifest_sha256": contract["execution_manifest_sha256"],
        "global_green_permitted": False,
        "key": solver_payload["key"],
        "schema": CHECKPOINT_SCHEMA,
        "shard": contract["shard"],
        "source_hashes": contract["source_hashes"],
    }


def _publish_key_artifacts(
    *,
    output_root: Path,
    contract: Mapping[str, object],
    plan: Mapping[str, object],
    key: RadialKey,
    solver_payload: Mapping[str, object],
) -> dict[str, object]:
    filenames = key_artifact_filenames(int(plan["shard_ordinal"]), key)
    payload_envelope = {
        "domain_contract_sha256": contract["domain_contract_sha256"],
        "domain_union_key_list_sha256": contract["domain_union_key_list_sha256"],
        "execution_contract_sha256": contract["execution_contract_sha256"],
        "execution_manifest_sha256": contract["execution_manifest_sha256"],
        "key": key.to_record(),
        "schema": KEY_PAYLOAD_ENVELOPE_SCHEMA,
        "shard": contract["shard"],
        "solver_payload": dict(solver_payload),
        "solver_payload_schema": SOLVER_PAYLOAD_SCHEMA,
    }
    payload_identity = _publish_json_exclusive(
        output_root / filenames["payload"], payload_envelope
    )
    checkpoint = _checkpoint_base(contract=contract, solver_payload=solver_payload)
    checkpoint["result_identity"] = {
        "mode": 0o444,
        "nlink": 1,
        "path": "pending",
        "sha256": "0" * 64,
        "size": 1,
    }
    result = {
        "acceptance_state": checkpoint["acceptance_state"],
        "actual_precision": checkpoint["actual_precision"],
        "domain_contract_sha256": checkpoint["domain_contract_sha256"],
        "domain_union_key_list_sha256": checkpoint["domain_union_key_list_sha256"],
        "execution_contract_sha256": checkpoint["execution_contract_sha256"],
        "execution_manifest_sha256": checkpoint["execution_manifest_sha256"],
        "key": checkpoint["key"],
        "observable_statuses": checkpoint["observable_statuses"],
        "payload_identity": payload_identity,
        "payload_schema": KEY_PAYLOAD_ENVELOPE_SCHEMA,
        "resume_claims_sha256": resume_claims_sha256(checkpoint),
        "schema": KEY_RESULT_SCHEMA,
        "shard": checkpoint["shard"],
    }
    result_identity = _publish_json_exclusive(output_root / filenames["result"], result)
    checkpoint["result_identity"] = result_identity
    checkpoint_identity = _publish_json_exclusive(
        output_root / filenames["checkpoint"], checkpoint
    )
    status = (
        "COMPLETED"
        if solver_payload["acceptance_state"] != "FAIL"
        else "COMPLETED_FAIL_CLOSED"
    )
    terminal = {
        "checkpoint_identity": checkpoint_identity,
        "domain_ordinal": plan["domain_ordinal"],
        "execution_status": status,
        "failure": None,
        "global_green_permitted": False,
        "key": key.to_record(),
        "predecessor": None,
        "schema": KEY_TERMINAL_SCHEMA,
        "shard_ordinal": plan["shard_ordinal"],
        "solver_call_count_this_run": solver_payload["total_solver_call_count"],
    }
    terminal_identity = _publish_json_exclusive(
        output_root / filenames["terminal"], terminal
    )
    return {
        "checkpoint": checkpoint,
        "checkpoint_identity": checkpoint_identity,
        "result_identity": result_identity,
        "terminal": terminal,
        "terminal_identity": terminal_identity,
    }


def _terminal_payload(
    *,
    plan: Mapping[str, object],
    key: RadialKey,
    execution_status: str,
    solver_call_count: int,
    checkpoint_identity: Mapping[str, object] | None,
    predecessor: Mapping[str, object] | None,
    failure: Mapping[str, str] | None,
) -> dict[str, object]:
    return {
        "checkpoint_identity": (
            None if checkpoint_identity is None else dict(checkpoint_identity)
        ),
        "domain_ordinal": plan["domain_ordinal"],
        "execution_status": execution_status,
        "failure": None if failure is None else dict(failure),
        "global_green_permitted": False,
        "key": key.to_record(),
        "predecessor": None if predecessor is None else dict(predecessor),
        "schema": KEY_TERMINAL_SCHEMA,
        "shard_ordinal": plan["shard_ordinal"],
        "solver_call_count_this_run": solver_call_count,
    }


def _validate_terminal(
    terminal: Mapping[str, object],
    *,
    plan: Mapping[str, object],
    key: RadialKey,
) -> None:
    if set(terminal) != {
        "checkpoint_identity",
        "domain_ordinal",
        "execution_status",
        "failure",
        "global_green_permitted",
        "key",
        "predecessor",
        "schema",
        "shard_ordinal",
        "solver_call_count_this_run",
    }:
        raise ShardRunError("key terminal exact schema changed")
    statuses = {
        "BLOCKED_NONREUSABLE_PREDECESSOR",
        "COMPLETED",
        "COMPLETED_FAIL_CLOSED",
        "EXECUTION_FAILED_AFTER_ARTIFACT_PUBLICATION",
        "EXECUTION_FAILED_AFTER_SOLVER_CALL",
        "NOT_STARTED_DUE_TO_SHARD_FAILURE",
        "REUSED_STRICT_PASS",
    }
    if (
        terminal.get("schema") != KEY_TERMINAL_SCHEMA
        or terminal.get("key") != key.to_record()
        or terminal.get("shard_ordinal") != plan["shard_ordinal"]
        or terminal.get("domain_ordinal") != plan["domain_ordinal"]
        or terminal.get("execution_status") not in statuses
        or terminal.get("global_green_permitted") is not False
        or isinstance(terminal.get("solver_call_count_this_run"), bool)
        or not isinstance(terminal.get("solver_call_count_this_run"), int)
        or terminal["solver_call_count_this_run"] < 0
    ):
        raise ShardRunError("key terminal key/order/status binding changed")
    status = terminal["execution_status"]
    checkpoint = terminal.get("checkpoint_identity")
    failure = terminal.get("failure")
    predecessor = terminal.get("predecessor")
    if checkpoint is not None and (
        not isinstance(checkpoint, Mapping)
        or set(checkpoint) != {"mode", "nlink", "path", "sha256", "size"}
    ):
        raise ShardRunError("key terminal checkpoint identity schema changed")
    if predecessor is not None and (
        not isinstance(predecessor, Mapping)
        or set(predecessor) != {"root", "terminal_identity"}
        or not isinstance(predecessor.get("root"), str)
        or not isinstance(predecessor.get("terminal_identity"), Mapping)
    ):
        raise ShardRunError("key terminal predecessor schema changed")
    if failure is not None and (
        not isinstance(failure, Mapping)
        or set(failure) != {"exception_type", "message", "stage"}
        or any(not isinstance(value, str) or not value for value in failure.values())
    ):
        raise ShardRunError("key terminal failure schema changed")
    if status in {"COMPLETED", "COMPLETED_FAIL_CLOSED"}:
        if checkpoint is None or failure is not None or predecessor is not None:
            raise ShardRunError("completed key terminal payload changed")
        if status == "COMPLETED" and terminal["solver_call_count_this_run"] < 1:
            raise ShardRunError("completed key terminal lacks a solver call")
    else:
        if status == "REUSED_STRICT_PASS":
            if (
                checkpoint is None
                or predecessor is None
                or failure is not None
                or terminal["solver_call_count_this_run"] != 0
            ):
                raise ShardRunError("reused key terminal payload changed")
        elif failure is None:
            raise ShardRunError("failed/not-started key terminal lacks a failure")
        elif status == "BLOCKED_NONREUSABLE_PREDECESSOR" and (
            predecessor is None or terminal["solver_call_count_this_run"] != 0
        ):
            raise ShardRunError("blocked predecessor terminal payload changed")
        elif status == "NOT_STARTED_DUE_TO_SHARD_FAILURE" and (
            checkpoint is not None or terminal["solver_call_count_this_run"] != 0
        ):
            raise ShardRunError("not-started key terminal payload changed")


def _predecessor_contract(
    resume_from: Path,
    current_contract: Mapping[str, object],
) -> Mapping[str, object]:
    if (
        resume_from.is_symlink()
        or not resume_from.is_dir()
        or resume_from.resolve(strict=True) != resume_from
        or stat.S_IMODE(resume_from.stat().st_mode) != 0o555
    ):
        raise ShardRunError("resume predecessor must be an immutable 0555 root")
    contract = _strict_json(resume_from / "run_contract.json")
    if (
        contract.get("schema") != RUN_CONTRACT_SCHEMA
        or contract.get("context_sha256") != current_contract["context_sha256"]
        or scan_context_hash(contract) != contract.get("context_sha256")
    ):
        raise ShardRunError("resume predecessor context identity changed")
    return contract


def _resume_or_block_terminal(
    *,
    output_root: Path,
    resume_from: Path,
    predecessor_contract: Mapping[str, object],
    plan: Mapping[str, object],
    key: RadialKey,
) -> tuple[bool, dict[str, object] | None]:
    filenames = key_artifact_filenames(int(plan["shard_ordinal"]), key)
    prior_terminal_path = resume_from / filenames["terminal"]
    prior_terminal = _strict_json(prior_terminal_path)
    _validate_terminal(prior_terminal, plan=plan, key=key)
    prior_terminal_identity = _validate_identity(
        source_file_identity(prior_terminal_path), path=prior_terminal_path
    )
    status = prior_terminal["execution_status"]
    if status == "NOT_STARTED_DUE_TO_SHARD_FAILURE":
        return False, None
    checkpoint_identity = prior_terminal.get("checkpoint_identity")
    if isinstance(checkpoint_identity, Mapping):
        checkpoint_path = Path(str(checkpoint_identity.get("path", "")))
        _validate_identity(checkpoint_identity, path=checkpoint_path)
        checkpoint = _strict_json(checkpoint_path)
        result_path = Path(str(checkpoint.get("result_identity", {}).get("path", "")))
        expected = _expected_key_context(
            predecessor_contract,
            plan,
            evidence_root=resume_from,
        )
        try:
            validate_resume_eligible(
                checkpoint,
                expected_context=expected,
                result_path=result_path,
            )
        except (ExecutionContractError, OSError, ValueError) as exc:
            failure = {
                "exception_type": type(exc).__name__,
                "message": str(exc) or "non-PASS predecessor cannot be reused",
                "stage": "strict_resume_gate",
            }
            terminal = _terminal_payload(
                plan=plan,
                key=key,
                execution_status="BLOCKED_NONREUSABLE_PREDECESSOR",
                solver_call_count=0,
                checkpoint_identity=checkpoint_identity,
                predecessor={
                    "root": str(resume_from),
                    "terminal_identity": prior_terminal_identity,
                },
                failure=failure,
            )
        else:
            terminal = _terminal_payload(
                plan=plan,
                key=key,
                execution_status="REUSED_STRICT_PASS",
                solver_call_count=0,
                checkpoint_identity=checkpoint_identity,
                predecessor={
                    "root": str(resume_from),
                    "terminal_identity": prior_terminal_identity,
                },
                failure=None,
            )
    else:
        failure = {
            "exception_type": "NonReusablePredecessor",
            "message": "predecessor terminal has no PASS checkpoint",
            "stage": "strict_resume_gate",
        }
        terminal = _terminal_payload(
            plan=plan,
            key=key,
            execution_status="BLOCKED_NONREUSABLE_PREDECESSOR",
            solver_call_count=0,
            checkpoint_identity=None,
            predecessor={
                "root": str(resume_from),
                "terminal_identity": prior_terminal_identity,
            },
            failure=failure,
        )
    _publish_json_exclusive(output_root / filenames["terminal"], terminal)
    return True, terminal


def _reload_terminals(
    root: Path,
    contract: Mapping[str, object],
) -> tuple[list[dict[str, object]], list[dict[str, object]]]:
    plans = contract["key_plans"]
    keys = [RadialKey.from_record(item) for item in contract["shard_keys"]]
    if not isinstance(plans, list) or len(plans) != len(keys):
        raise ShardRunError("run contract key-plan cardinality changed")
    records: list[dict[str, object]] = []
    identities: list[dict[str, object]] = []
    for plan, key in zip(plans, keys, strict=True):
        filenames = key_artifact_filenames(int(plan["shard_ordinal"]), key)
        path = root / filenames["terminal"]
        terminal = _strict_json(path)
        _validate_terminal(terminal, plan=plan, key=key)
        records.append(terminal)
        identities.append(_validate_identity(source_file_identity(path), path=path))
    return records, identities


def _status_worst(values: Sequence[str]) -> str:
    rank = {"PASS": 0, "NOT_ASSESSED": 1, "PARTIAL": 2, "FAIL": 3}
    return max(values, key=rank.__getitem__) if values else "NOT_ASSESSED"


def _aggregate_shard(
    *,
    contract: Mapping[str, object],
    terminals: Sequence[Mapping[str, object]],
    terminal_identities: Sequence[Mapping[str, object]],
) -> tuple[dict[str, object], dict[str, object]]:
    consumed_checkpoints: list[Mapping[str, object]] = []
    consumed_checkpoint_identities: list[dict[str, object]] = []
    blocked = 0
    reused = 0
    for terminal in terminals:
        status = terminal["execution_status"]
        reused += int(status == "REUSED_STRICT_PASS")
        blocked += int(status == "BLOCKED_NONREUSABLE_PREDECESSOR")
        identity = terminal.get("checkpoint_identity")
        if isinstance(identity, Mapping) and status in {
            "COMPLETED",
            "COMPLETED_FAIL_CLOSED",
            "REUSED_STRICT_PASS",
        }:
            checkpoint_path = Path(str(identity["path"]))
            consumed_checkpoint_identities.append(
                _validate_identity(identity, path=checkpoint_path)
            )
            consumed_checkpoints.append(_strict_json(checkpoint_path))
    numerical_statuses = [
        str(checkpoint["numerical_budget"]["status"])
        for checkpoint in consumed_checkpoints
    ]
    convention_statuses = [
        str(checkpoint["convention_budget"]["status"])
        for checkpoint in consumed_checkpoints
    ]
    observable_names = {
        name
        for checkpoint in consumed_checkpoints
        for name in checkpoint["observable_statuses"]
    }
    observable_statuses = {
        name: _status_worst(
            [
                str(checkpoint["observable_statuses"].get(name, "NOT_ASSESSED"))
                for checkpoint in consumed_checkpoints
            ]
        )
        for name in sorted(observable_names)
    }
    attempts = [
        {
            "attempt": 1,
            "status": (
                "FAIL"
                if blocked
                or any(
                    terminal["execution_status"]
                    in {
                        "COMPLETED_FAIL_CLOSED",
                        "EXECUTION_FAILED_AFTER_ARTIFACT_PUBLICATION",
                        "EXECUTION_FAILED_AFTER_SOLVER_CALL",
                        "NOT_STARTED_DUE_TO_SHARD_FAILURE",
                    }
                    for terminal in terminals
                )
                else "PARTIAL"
            ),
        }
    ]
    execution_failed = attempts[-1]["status"] == "FAIL"
    numerical_components = {
        name: (
            float(np.finfo(float).max)
            if execution_failed or not consumed_checkpoints
            else max(
                float(checkpoint["numerical_budget"]["components"][name])
                for checkpoint in consumed_checkpoints
            )
        )
        for name in NUMERICAL_BUDGET_FIELDS
    }
    convention_components = {
        name: (
            float(np.finfo(float).max)
            if execution_failed or not consumed_checkpoints
            else max(
                float(checkpoint["convention_budget"]["components"][name])
                for checkpoint in consumed_checkpoints
            )
        )
        for name in CONVENTION_BUDGET_FIELDS
    }
    shard_result = {
        "acceptance_state": _status_worst(
            [
                str(checkpoint.get("acceptance_state", "NOT_ASSESSED"))
                for checkpoint in consumed_checkpoints
            ]
            + (["FAIL"] if blocked else [])
        ),
        "global_green_permitted": False,
        "key_terminal_identities": [dict(item) for item in terminal_identities],
        "observable_statuses": observable_statuses,
        "paper_figure_runs": 0,
        "schema": SHARD_RESULT_SCHEMA,
        "shard": contract["shard"],
        "summary": {
            "blocked_nonreusable_predecessor_count": blocked,
            "key_count": len(terminals),
            "reused_strict_pass_count": reused,
            "solver_call_count_this_run": sum(
                int(terminal["solver_call_count_this_run"]) for terminal in terminals
            ),
        },
    }
    shard_checkpoint = {
        "attempts": attempts,
        "backend_hashes": contract["backend_hashes"],
        "code_hashes": contract["code_hashes"],
        "config_hashes": contract["config_hashes"],
        "convention_budget": {
            "components": convention_components,
            "status": (
                "FAIL" if execution_failed else _status_worst(convention_statuses)
            ),
        },
        "domain_contract_sha256": contract["domain_contract_sha256"],
        "domain_union_key_list_sha256": contract["domain_union_key_list_sha256"],
        "global_green_permitted": False,
        "key_checkpoint_identities": consumed_checkpoint_identities,
        "key_list_sha256": contract["shard"]["key_list_sha256"],
        "numerical_budget": {
            "components": numerical_components,
            "status": (
                "FAIL" if execution_failed else _status_worst(numerical_statuses)
            ),
        },
        "observable_statuses": observable_statuses,
        "schema": SHARD_CHECKPOINT_SCHEMA,
        "shard_id": contract["shard"]["shard_id"],
        "source_hashes": contract["source_hashes"],
    }
    return shard_result, shard_checkpoint


def _ensure_missing_terminals(
    *,
    output_root: Path,
    contract: Mapping[str, object],
    stage: str,
    exc: Exception,
    solver_call_counts: Mapping[RadialKey, int],
) -> list[dict[str, str]]:
    errors: list[dict[str, str]] = []
    plans = contract["key_plans"]
    keys = [RadialKey.from_record(item) for item in contract["shard_keys"]]
    failure = {
        "exception_type": type(exc).__name__,
        "message": str(exc) or "<empty exception message>",
        "stage": stage,
    }
    for plan, key in zip(plans, keys, strict=True):
        filenames = key_artifact_filenames(int(plan["shard_ordinal"]), key)
        terminal_path = output_root / filenames["terminal"]
        if terminal_path.exists() or terminal_path.is_symlink():
            try:
                _validate_terminal(
                    _strict_json(terminal_path),
                    plan=plan,
                    key=key,
                )
            except Exception as terminal_exc:
                errors.append(
                    {
                        "error": f"{type(terminal_exc).__name__}: {terminal_exc}",
                        "key": json.dumps(key.to_record(), sort_keys=True),
                    }
                )
            continue
        checkpoint_path = output_root / filenames["checkpoint"]
        try:
            checkpoint_identity = (
                source_file_identity(checkpoint_path)
                if checkpoint_path.is_file() and not checkpoint_path.is_symlink()
                else None
            )
            artifacts_started = any(
                (output_root / filenames[name]).exists()
                for name in ("payload", "result", "checkpoint")
            )
            if artifacts_started:
                status = "EXECUTION_FAILED_AFTER_ARTIFACT_PUBLICATION"
            elif solver_call_counts.get(key, 0) > 0:
                status = "EXECUTION_FAILED_AFTER_SOLVER_CALL"
            else:
                status = "NOT_STARTED_DUE_TO_SHARD_FAILURE"
            terminal = _terminal_payload(
                plan=plan,
                key=key,
                execution_status=status,
                solver_call_count=solver_call_counts.get(key, 0),
                checkpoint_identity=checkpoint_identity,
                predecessor=None,
                failure=failure,
            )
            _publish_json_exclusive(terminal_path, terminal)
        except Exception as terminal_exc:
            errors.append(
                {
                    "error": f"{type(terminal_exc).__name__}: {terminal_exc}",
                    "key": json.dumps(key.to_record(), sort_keys=True),
                }
            )
    return errors


def _seal_root(root: Path) -> None:
    if root.is_symlink() or root.resolve(strict=True) != root:
        raise ShardRunError("cannot seal an aliased shard root")
    os.chmod(root, 0o555)
    _fsync_directory(root.parent)


def _make_root_writable_for_failure(root: Path) -> None:
    if root.is_symlink() or root.resolve(strict=True) != root:
        raise ShardRunError("cannot recover an aliased shard root")
    mode = stat.S_IMODE(root.stat().st_mode)
    if mode == 0o555:
        os.chmod(root, 0o700)
        _fsync_directory(root.parent)
    elif mode != 0o700:
        raise ShardRunError("allocated shard root has an unexpected mode")


def _validate_completed_root(
    root: Path,
    contract: Mapping[str, object],
) -> None:
    if (
        root.is_symlink()
        or root.resolve(strict=True) != root
        or stat.S_IMODE(root.stat().st_mode) != 0o555
    ):
        raise ShardRunError("completed shard root is not immutable 0555")
    reloaded_contract = _strict_json(root / "run_contract.json")
    if (
        reloaded_contract != dict(contract)
        or scan_context_hash(reloaded_contract) != contract["context_sha256"]
    ):
        raise ShardRunError("completed run contract identity changed")
    terminals, terminal_identities = _reload_terminals(root, contract)
    manifest = _strict_json(root / "manifest.json")
    shard_result = _strict_json(root / "shard_result.json")
    shard_checkpoint = _strict_json(root / "shard_checkpoint.json")
    if set(manifest) != {
        "created_at_utc",
        "elapsed_seconds",
        "global_green_permitted",
        "key_terminal_identities",
        "paper_figure_runs",
        "run_contract_identity",
        "schema",
        "shard_checkpoint_identity",
        "shard_result_identity",
    }:
        raise ShardRunError("completed manifest exact schema changed")
    if (
        manifest.get("schema") != "schwgw_phase6_conditioning_shard_manifest_v1"
        or manifest.get("global_green_permitted") is not False
        or manifest.get("paper_figure_runs") != 0
        or manifest.get("key_terminal_identities") != terminal_identities
    ):
        raise ShardRunError("completed manifest claims changed")
    _validate_identity(
        manifest["run_contract_identity"], path=root / "run_contract.json"
    )
    _validate_identity(
        manifest["shard_result_identity"], path=root / "shard_result.json"
    )
    _validate_identity(
        manifest["shard_checkpoint_identity"], path=root / "shard_checkpoint.json"
    )
    if (
        shard_result.get("schema") != SHARD_RESULT_SCHEMA
        or shard_checkpoint.get("schema") != SHARD_CHECKPOINT_SCHEMA
        or shard_checkpoint.get("result_identity") != manifest["shard_result_identity"]
        or shard_result.get("global_green_permitted") is not False
        or shard_checkpoint.get("global_green_permitted") is not False
    ):
        raise ShardRunError("completed shard aggregate linkage changed")
    plans = contract["key_plans"]
    keys = [RadialKey.from_record(item) for item in contract["shard_keys"]]
    allowed = {
        "run_contract.json",
        "shard_result.json",
        "shard_checkpoint.json",
        "manifest.json",
    }
    for plan, key, terminal in zip(plans, keys, terminals, strict=True):
        filenames = key_artifact_filenames(int(plan["shard_ordinal"]), key)
        allowed.add(filenames["terminal"])
        status = terminal["execution_status"]
        if status in {"COMPLETED", "COMPLETED_FAIL_CLOSED"}:
            allowed.update(
                {
                    filenames["payload"],
                    filenames["result"],
                    filenames["checkpoint"],
                }
            )
            checkpoint_path = root / filenames["checkpoint"]
            _validate_identity(terminal["checkpoint_identity"], path=checkpoint_path)
            checkpoint = _strict_json(checkpoint_path)
            result_path = root / filenames["result"]
            validate_key_checkpoint(
                checkpoint,
                expected_context=_expected_key_context(
                    contract,
                    plan,
                    evidence_root=root,
                ),
                result_path=result_path,
            )
        elif status in {
            "BLOCKED_NONREUSABLE_PREDECESSOR",
            "REUSED_STRICT_PASS",
        }:
            predecessor = terminal["predecessor"]
            predecessor_root = Path(str(predecessor["root"]))
            expected_predecessor = contract.get("resume_from")
            if str(predecessor_root) != expected_predecessor:
                raise ShardRunError("terminal predecessor root changed")
            predecessor_terminal_path = Path(
                str(predecessor["terminal_identity"]["path"])
            )
            if predecessor_terminal_path != predecessor_root / filenames["terminal"]:
                raise ShardRunError("terminal predecessor linkage changed")
            _validate_identity(
                predecessor["terminal_identity"],
                path=predecessor_terminal_path,
            )
            checkpoint_identity = terminal.get("checkpoint_identity")
            if isinstance(checkpoint_identity, Mapping):
                checkpoint_path = Path(str(checkpoint_identity["path"]))
                _validate_identity(checkpoint_identity, path=checkpoint_path)
            if status == "REUSED_STRICT_PASS":
                predecessor_contract = _strict_json(
                    predecessor_root / "run_contract.json"
                )
                checkpoint = _strict_json(checkpoint_path)
                validate_resume_eligible(
                    checkpoint,
                    expected_context=_expected_key_context(
                        predecessor_contract,
                        plan,
                        evidence_root=predecessor_root,
                    ),
                    result_path=Path(str(checkpoint["result_identity"]["path"])),
                )
        else:
            raise ShardRunError("completed root contains an execution-failure terminal")
    actual = {path.name for path in root.iterdir()}
    if actual != allowed:
        raise ShardRunError("completed shard root file inventory changed")
    for path in root.iterdir():
        if (
            path.is_symlink()
            or not path.is_file()
            or stat.S_IMODE(path.stat().st_mode) != 0o444
        ):
            raise ShardRunError("completed shard root contains a mutable artifact")


def _validate_failed_root(
    root: Path,
    contract: Mapping[str, object],
    *,
    terminal_protocol_errors: Sequence[Mapping[str, str]],
) -> None:
    if (
        root.is_symlink()
        or root.resolve(strict=True) != root
        or stat.S_IMODE(root.stat().st_mode) != 0o555
    ):
        raise ShardRunError("failed shard root is not immutable 0555")
    failure = _strict_json(root / "failure.json")
    if set(failure) != {
        "exception",
        "global_green_permitted",
        "paper_figure_runs",
        "run_contract_identity",
        "schema",
        "status",
        "terminal_protocol_errors",
    } or (
        failure.get("schema") != SHARD_FAILURE_SCHEMA
        or failure.get("status") != "FAIL_CLOSED_EXECUTION"
        or failure.get("global_green_permitted") is not False
        or failure.get("paper_figure_runs") != 0
        or failure.get("terminal_protocol_errors")
        != [dict(item) for item in terminal_protocol_errors]
    ):
        raise ShardRunError("failed shard exact schema changed")
    contract_identity = failure.get("run_contract_identity")
    if (root / "run_contract.json").is_file():
        _validate_identity(contract_identity, path=root / "run_contract.json")
        if _strict_json(root / "run_contract.json") != dict(contract):
            raise ShardRunError("failed shard run contract changed")
    elif contract_identity is not None:
        raise ShardRunError("failed shard has a dangling run-contract identity")
    if not terminal_protocol_errors:
        _reload_terminals(root, contract)
    for path in root.iterdir():
        if (
            path.is_symlink()
            or not path.is_file()
            or stat.S_IMODE(path.stat().st_mode) != 0o444
        ):
            raise ShardRunError("failed shard root contains a mutable artifact")


def run_shard(
    output_root: Path,
    *,
    shard_id: str,
    resume_from: Path | None = None,
    policy: ConditioningPolicy = DEFAULT_POLICY,
    selector: Selector | None = None,
    solver: ConditionedSolver | None = None,
    test_mode: bool = False,
) -> dict[str, object]:
    """Run one fresh shard with no retry and exact immutable terminals."""

    if (selector is not None or solver is not None) and not test_mode:
        raise ShardRunError(
            "selector/solver injection requires explicit test_mode=True"
        )
    if test_mode and selector is None and solver is None:
        raise ShardRunError("test_mode requires an explicit test injection")
    output = output_root.resolve(strict=False)
    if output != output_root or output.exists() or output.is_symlink():
        raise FileExistsError("output root must be a fresh absolute canonical path")
    if not output.parent.is_dir() or output.parent.is_symlink():
        raise ShardRunError("output parent must be an existing direct directory")
    frozen = load_frozen_scan_contract(DOMAIN_ROOT, EXECUTION_ROOT)
    actual_selector = selector or (
        lambda key: select_outer_boundary(key, policy=policy)
    )
    predecessor = None
    if resume_from is not None:
        resolved_predecessor = resume_from.resolve(strict=True)
        if resume_from.is_symlink() or resume_from != resolved_predecessor:
            raise ShardRunError(
                "resume predecessor must be an absolute canonical direct path"
            )
        predecessor = resolved_predecessor
    contract, selections = _build_run_contract(
        frozen=frozen,
        shard_id=shard_id,
        output_root=output,
        resume_from=predecessor,
        policy=policy,
        selector=actual_selector,
        test_mode=test_mode,
        selector_injected=selector is not None,
        solver_injected=solver is not None,
    )
    predecessor_contract = (
        None if predecessor is None else _predecessor_contract(predecessor, contract)
    )
    output.mkdir(mode=0o700)
    os.chmod(output, 0o700)
    stage = "run_contract_publication"
    started = time.perf_counter()
    plans = contract["key_plans"]
    keys = [RadialKey.from_record(item) for item in contract["shard_keys"]]
    solver_call_counts: dict[RadialKey, int] = {}
    try:
        _publish_json_exclusive(output / "run_contract.json", contract)
        for plan, key in zip(plans, keys, strict=True):
            stage = f"key:{plan['shard_ordinal']}"
            if predecessor is not None and predecessor_contract is not None:
                consumed, _ = _resume_or_block_terminal(
                    output_root=output,
                    resume_from=predecessor,
                    predecessor_contract=predecessor_contract,
                    plan=plan,
                    key=key,
                )
                if consumed:
                    continue
            selection_record = plan["outer_selection"]
            if not isinstance(selection_record, Mapping):
                raise ShardRunError("run plan outer selection is malformed")
            selection = selections[key]
            if selection.to_record() != selection_record:
                raise ShardRunError("frozen in-memory selector result changed")
            if solver is None:
                solver_payload = execute_key_scan(
                    key,
                    selection,
                    transition_key=bool(plan["transition_key"]),
                    policy=policy,
                )
            else:
                solver_payload = execute_key_scan(
                    key,
                    selection,
                    transition_key=bool(plan["transition_key"]),
                    policy=policy,
                    solver=solver,
                )
            solver_call_counts[key] = int(solver_payload["total_solver_call_count"])
            _publish_key_artifacts(
                output_root=output,
                contract=contract,
                plan=plan,
                key=key,
                solver_payload=solver_payload,
            )
        stage = "terminal_reload"
        terminals, terminal_identities = _reload_terminals(output, contract)
        shard_result, shard_checkpoint = _aggregate_shard(
            contract=contract,
            terminals=terminals,
            terminal_identities=terminal_identities,
        )
        shard_result_identity = _publish_json_exclusive(
            output / "shard_result.json", shard_result
        )
        shard_checkpoint["result_identity"] = shard_result_identity
        shard_checkpoint_identity = _publish_json_exclusive(
            output / "shard_checkpoint.json", shard_checkpoint
        )
        manifest = {
            "created_at_utc": datetime.now(timezone.utc).isoformat(),
            "elapsed_seconds": time.perf_counter() - started,
            "global_green_permitted": False,
            "key_terminal_identities": terminal_identities,
            "paper_figure_runs": 0,
            "run_contract_identity": source_file_identity(output / "run_contract.json"),
            "schema": "schwgw_phase6_conditioning_shard_manifest_v1",
            "shard_checkpoint_identity": shard_checkpoint_identity,
            "shard_result_identity": shard_result_identity,
        }
        manifest_identity = _publish_json_exclusive(output / "manifest.json", manifest)
        _seal_root(output)
        _validate_completed_root(output, contract)
        return {
            "manifest_identity": manifest_identity,
            "root": str(output),
            "shard_checkpoint_identity": shard_checkpoint_identity,
            "shard_id": shard_id,
            "shard_result_identity": shard_result_identity,
            "status": shard_result["acceptance_state"],
        }
    except Exception as exc:
        _make_root_writable_for_failure(output)
        terminal_errors = _ensure_missing_terminals(
            output_root=output,
            contract=contract,
            stage=stage,
            exc=exc,
            solver_call_counts=solver_call_counts,
        )
        failure = {
            "exception": {
                "exception_type": type(exc).__name__,
                "message": str(exc) or "<empty exception message>",
                "stage": stage,
            },
            "global_green_permitted": False,
            "paper_figure_runs": 0,
            "run_contract_identity": (
                source_file_identity(output / "run_contract.json")
                if (output / "run_contract.json").is_file()
                and not (output / "run_contract.json").is_symlink()
                else None
            ),
            "schema": SHARD_FAILURE_SCHEMA,
            "status": "FAIL_CLOSED_EXECUTION",
            "terminal_protocol_errors": terminal_errors,
        }
        failure_identity = _publish_json_exclusive(output / "failure.json", failure)
        _seal_root(output)
        _validate_failed_root(
            output,
            contract,
            terminal_protocol_errors=terminal_errors,
        )
        raise ShardRunError(
            f"conditioning shard failed closed; failure={failure_identity['path']}"
        ) from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-root", required=True, type=Path)
    parser.add_argument("--shard-id", required=True)
    parser.add_argument("--resume-from", type=Path)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    result = run_shard(
        args.output_root,
        shard_id=args.shard_id,
        resume_from=args.resume_from,
    )
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
