"""Fail-closed Phase-6 V1 release ledger.

The release layer is deliberately a *certifier*, not a numerical producer.
It binds the four authoritative Phase-6 contracts, immutable evidence
envelopes, and per-observable/per-domain certificates.  It never derives a
project-wide colour or uses paper-figure agreement as a primary gate.

Evidence generated by heterogeneous producers is normalized by a small
immutable envelope.  The envelope does not replace the source evidence: it
contains live identities for the already frozen source artifacts.  This
allows the release validator to reject mutable, missing, duplicated, aliased,
contract-only, or blocker-only evidence before a certificate is published.
"""

from __future__ import annotations

from collections import Counter
from collections.abc import Mapping, Sequence
from decimal import Decimal, InvalidOperation
import hashlib
import json
import math
from pathlib import Path
import re
import stat

from schwgw.validation.phase6_domain import canonical_json_bytes


SUBMISSION_SCHEMA = "schwgw_phase6_v1_release_submission_v1"
LEDGER_SCHEMA = "schwgw_phase6_v1_release_ledger_v1"
MANIFEST_SCHEMA = "schwgw_phase6_v1_release_manifest_v1"
EVIDENCE_ENVELOPE_SCHEMA = "schwgw_phase6_v1_release_evidence_envelope_v1"
CERTIFICATE_SCHEMA = "schwgw_phase6_v1_release_certificate_v1"

STATES = ("NOT_ASSESSED", "PARTIAL", "PASS", "FAIL")
GATES = ("V0", "V1", "V1Q", "V2", "V3", "V4", "V5", "V6")
EVIDENCE_ROLES = (
    "PRIMARY_SCIENCE",
    "INDEPENDENT_SCIENCE",
    "IMPLEMENTATION_VERIFICATION",
    "POLICY_VERIFICATION",
    "CONVENTION_DEFINITION",
    "BLOCKER",
    "FAILURE_DIAGNOSTIC",
    "SECONDARY_PAPER_REGRESSION",
    "CONTRACT_ONLY",
)
INDEPENDENCE_CLASSES = (
    "SAME_IMPLEMENTATION",
    "ALGORITHMICALLY_INDEPENDENT",
    "EXTERNAL_SOURCE",
    "NONE",
)
MEDIA_TYPES = (
    "application/json",
    "application/x-jsonlines",
    "application/octet-stream",
)
SOURCE_ARTIFACT_ROLES = (
    "RESULT",
    "INPUT",
    "CONFIG",
    "SOURCE_SNAPSHOT",
    "THRESHOLD",
    "CONVENTION",
)
NUMERICAL_BUDGET_FIELDS = (
    "lmax",
    "r_in",
    "r_out",
    "jost_order",
    "ode_tolerance",
    "arithmetic_precision",
    "axis_limit",
    "backend_difference",
)
CONVENTION_BUDGET_FIELDS = (
    "observer",
    "worldline",
    "tetrad",
    "polarization_basis",
    "phase_origin",
    "total_scattered_definition",
)

GATE_OBSERVABLES: dict[str, tuple[str, ...]] = {
    "V0": ("claim_provenance_cleanup",),
    "V1": ("radial_s_matrix_flux",),
    "V1Q": ("generic_conditioning_backend",),
    "V2": ("master_to_strain_flux", "metric_psi4_external_crosscheck"),
    "V3": ("spin2_scattering_limits",),
    "V4": ("finite_radius_tidal_detector",),
    "V5": ("complex_lensing_matrix",),
    "V6": ("release_uncertainty_policy",),
}
REQUIRED_LEDGER_SLICES = frozenset(
    (gate, observable)
    for gate, observables in GATE_OBSERVABLES.items()
    for observable in observables
)
PHYSICAL_GATES = frozenset({"V1", "V1Q", "V2", "V3", "V4", "V5"})

PROJECT_ROOT = Path(__file__).resolve().parents[3]
_CONTRACT_SPECS: dict[str, dict[str, object]] = {
    "domain_v3": {
        "root": PROJECT_ROOT / "runs/phase6/v1_domain_freeze_v3_20260806",
        "contract_filename": "domain_contract.json",
        "contract_sha256": (
            "7ed99b905c3a1301d96101f357ab1fd9f4bc6e9a4922cb242d28e7cf06bb3bcf"
        ),
        "manifest_sha256": (
            "f11d127e0bcfafa8f2fe24b2d3cec3e0cedc60f644d4285e6d52e53d8358d2d2"
        ),
        "schema": "schwgw_phase6_v1_domain_contract_v1",
    },
    "execution_v4": {
        "root": PROJECT_ROOT / "runs/phase6/v1_execution_contract_v4_20260806",
        "contract_filename": "execution_contract.json",
        "contract_sha256": (
            "25ad4b4e723edbd44651edaa63df415141de504b85288b12c2a6a973fcb420ab"
        ),
        "manifest_sha256": (
            "1de9d445d888cbb5ddbf426cc062d2fb5128cad111437ce7d147df6e004aed48"
        ),
        "schema": "schwgw_phase6_v1_execution_contract_v1",
    },
    "aggregation_v8": {
        "root": PROJECT_ROOT / "runs/phase6/v1_aggregation_contract_v8_20260806",
        "contract_filename": "aggregation_contract.json",
        "contract_sha256": (
            "742db1cf159e0bb9c41eb2621b7084f09bca65acd934fdcf639f25f486fa49d2"
        ),
        "manifest_sha256": (
            "427ddf4984690e930b225f0a3c782b99cbf65eb1a30fcb77f8f1ee67ab53675c"
        ),
        "schema": "schwgw_phase6_v1_aggregation_contract_v1",
    },
    "observable_v2": {
        "root": PROJECT_ROOT / "runs/phase6/v1_observable_contract_v2_20260806",
        "contract_filename": "observable_contract.json",
        "contract_sha256": (
            "3853df8fbc245b81552198d99201778e4020d82f618e3f80ac745768fc3d104b"
        ),
        "manifest_sha256": (
            "799f8d9d315a1be04ef0bb7cf31040230dac6a618fee8b43a01b0855515bb81c"
        ),
        "schema": "schwgw_phase6_v1_observable_contract_v2",
    },
}

_ID = re.compile(r"[a-z0-9][a-z0-9_.-]{0,95}")
_SHA256 = re.compile(r"[0-9a-f]{64}")
_BLOCKER_CODE = re.compile(r"[A-Z][A-Z0-9_]{0,95}")
_FORBIDDEN_PRIMARY = re.compile(r"(?:\bli\b|paper[ _-]?fig|raster)", re.I)
_FORBIDDEN_GLOBAL_CLAIM = re.compile(
    r"(?:global|project(?:-wide)?|schwo).{0,24}(?:green|pass(?:ed)?)",
    re.I,
)


class Phase6ReleaseError(ValueError):
    """Raised for an unsafe, stale, ambiguous, or overclaimed release."""


def has_forbidden_global_claim(value: str) -> bool:
    """Return whether release-facing prose claims a project-wide status."""

    return _FORBIDDEN_GLOBAL_CLAIM.search(value) is not None


def sha256_bytes(data: bytes) -> str:
    """Return the SHA-256 digest used by release artifacts."""

    return hashlib.sha256(data).hexdigest()


def _exact(value: object, fields: set[str], label: str) -> Mapping[str, object]:
    if not isinstance(value, Mapping) or set(value) != fields:
        raise Phase6ReleaseError(f"{label} schema changed")
    return value


def _required_text(value: object, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise Phase6ReleaseError(f"{label} must be non-empty text")
    return value


def _identifier(value: object, label: str) -> str:
    text = _required_text(value, label)
    if not _ID.fullmatch(text):
        raise Phase6ReleaseError(f"{label} is not a canonical identifier")
    return text


def _json_value(value: object, label: str) -> None:
    """Allow exact JSON values while prohibiting binary floating-point input."""

    if value is None or isinstance(value, (str, bool)):
        return
    if isinstance(value, int) and not isinstance(value, bool):
        return
    if isinstance(value, list):
        for index, item in enumerate(value):
            _json_value(item, f"{label}[{index}]")
        return
    if isinstance(value, Mapping):
        if any(not isinstance(key, str) or not key for key in value):
            raise Phase6ReleaseError(f"{label} contains an invalid key")
        for key, item in value.items():
            _json_value(item, f"{label}.{key}")
        return
    raise Phase6ReleaseError(f"{label} contains a float or unsupported value")


def _finite_json_value(value: object, label: str) -> None:
    """Permit source-artifact floats, but never NaN or infinity."""

    if value is None or isinstance(value, (str, bool)):
        return
    if isinstance(value, int) and not isinstance(value, bool):
        return
    if isinstance(value, float):
        if not math.isfinite(value):
            raise Phase6ReleaseError(f"{label} contains a non-finite float")
        return
    if isinstance(value, list):
        for index, item in enumerate(value):
            _finite_json_value(item, f"{label}[{index}]")
        return
    if isinstance(value, Mapping):
        if any(not isinstance(key, str) or not key for key in value):
            raise Phase6ReleaseError(f"{label} contains an invalid key")
        for key, item in value.items():
            _finite_json_value(item, f"{label}.{key}")
        return
    raise Phase6ReleaseError(f"{label} contains an unsupported JSON value")


def _decimal(value: object, label: str, *, nonnegative: bool = True) -> Decimal:
    if (
        not isinstance(value, str)
        or not value
        or "e" in value.lower()
        or value.startswith("+")
    ):
        raise Phase6ReleaseError(f"{label} must be a canonical decimal string")
    try:
        number = Decimal(value)
    except InvalidOperation as exc:
        raise Phase6ReleaseError(f"{label} is not decimal") from exc
    if not number.is_finite() or format(number, "f") != value:
        raise Phase6ReleaseError(f"{label} must be a canonical decimal string")
    if nonnegative and number < 0:
        raise Phase6ReleaseError(f"{label} must be nonnegative")
    return number


def direct_file_identity(path: str | Path) -> dict[str, object]:
    """Identify a frozen direct file and reject aliases or mutable roots."""

    absolute = Path(path).absolute()
    if any(component.is_symlink() for component in (absolute, *absolute.parents)):
        raise Phase6ReleaseError("evidence path contains a symlink component")
    try:
        resolved = absolute.resolve(strict=True)
        info = absolute.lstat()
        parent_info = absolute.parent.lstat()
    except OSError as exc:
        raise Phase6ReleaseError(f"cannot identify frozen file: {absolute}") from exc
    if (
        resolved != absolute
        or not stat.S_ISREG(info.st_mode)
        or info.st_nlink != 1
        or stat.S_IMODE(info.st_mode) != 0o444
    ):
        raise Phase6ReleaseError("evidence must be a direct regular 0444 nlink1 file")
    if (
        absolute.parent.is_symlink()
        or not stat.S_ISDIR(parent_info.st_mode)
        or stat.S_IMODE(parent_info.st_mode) != 0o555
    ):
        raise Phase6ReleaseError("evidence parent must be a direct mode 0555 root")
    return {
        "mode": stat.S_IMODE(info.st_mode),
        "nlink": info.st_nlink,
        "path": str(absolute),
        "sha256": sha256_bytes(absolute.read_bytes()),
        "size": info.st_size,
    }


def _identity(value: object, label: str) -> Mapping[str, object]:
    item = _exact(value, {"mode", "nlink", "path", "sha256", "size"}, label)
    if (
        not isinstance(item["path"], str)
        or not isinstance(item["sha256"], str)
        or not _SHA256.fullmatch(str(item["sha256"]))
        or isinstance(item["mode"], bool)
        or not isinstance(item["mode"], int)
        or isinstance(item["nlink"], bool)
        or not isinstance(item["nlink"], int)
        or isinstance(item["size"], bool)
        or not isinstance(item["size"], int)
        or item["size"] < 0
    ):
        raise Phase6ReleaseError(f"{label} identity types changed")
    actual = direct_file_identity(str(item["path"]))
    if dict(item) != actual:
        raise Phase6ReleaseError(f"{label} identity no longer matches live bytes")
    return item


def _canonical_json(identity: object, label: str) -> Mapping[str, object]:
    checked = _identity(identity, label)
    raw = Path(str(checked["path"])).read_bytes()
    try:
        payload = json.loads(raw)
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise Phase6ReleaseError(f"{label} is not JSON") from exc
    if not isinstance(payload, Mapping) or canonical_json_bytes(payload) != raw:
        raise Phase6ReleaseError(f"{label} is not a canonical JSON object")
    _finite_json_value(payload, label)
    return payload


def _canonical_jsonl(identity: object, label: str) -> tuple[Mapping[str, object], ...]:
    checked = _identity(identity, label)
    raw = Path(str(checked["path"])).read_bytes()
    if raw and not raw.endswith(b"\n"):
        raise Phase6ReleaseError(f"{label} lacks its final LF")
    records: list[Mapping[str, object]] = []
    for index, line in enumerate(raw.splitlines(keepends=True)):
        try:
            record = json.loads(line)
        except (json.JSONDecodeError, UnicodeDecodeError) as exc:
            raise Phase6ReleaseError(f"{label}[{index}] is not JSON") from exc
        if (
            not isinstance(record, Mapping)
            or not record
            or canonical_json_bytes(record) != line
        ):
            raise Phase6ReleaseError(f"{label}[{index}] is not canonical JSONL")
        _finite_json_value(record, f"{label}[{index}]")
        records.append(record)
    canonical = [canonical_json_bytes(record) for record in records]
    if len(set(canonical)) != len(canonical):
        raise Phase6ReleaseError(f"{label} contains duplicate JSONL records")
    return tuple(records)


def authoritative_contract_bindings() -> dict[str, dict[str, object]]:
    """Return live identities for the four authoritative frozen contracts."""

    result: dict[str, dict[str, object]] = {}
    for label, spec in _CONTRACT_SPECS.items():
        root = Path(str(spec["root"]))
        result[label] = {
            "contract_identity": direct_file_identity(
                root / str(spec["contract_filename"])
            ),
            "manifest_identity": direct_file_identity(root / "manifest.json"),
        }
    validate_contract_bindings(result)
    return result


def _validate_contract_payload(label: str, payload: Mapping[str, object]) -> None:
    spec = _CONTRACT_SPECS[label]
    if payload.get("schema") != spec["schema"]:
        raise Phase6ReleaseError(f"{label} contract schema changed")
    if label == "domain_v3":
        files = payload.get("domain_files")
        counts = {
            "D_prod.jsonl": 16048,
            "D_ext.jsonl": 1770,
            "D_required.jsonl": 3392,
            "D_union.jsonl": 17818,
        }
        if payload.get("global_green_permitted") is not False or not isinstance(
            files, Mapping
        ):
            raise Phase6ReleaseError("domain v3 policy changed")
        if any(
            not isinstance(files.get(name), Mapping)
            or files[name].get("count") != count
            for name, count in counts.items()
        ):
            raise Phase6ReleaseError("domain v3 cardinality changed")
    elif label == "execution_v4":
        acceptance = payload.get("domain_acceptance")
        external = payload.get("external_direct_calibration")
        transition = payload.get("generic_transition_calibration")
        shards = payload.get("shard_inventory")
        if (
            not isinstance(acceptance, Mapping)
            or acceptance.get("global_green_permitted") is not False
            or acceptance.get("paper_agreement_gate") != "PROHIBITED"
            or not isinstance(external, Mapping)
            or external.get("count") != 30
            or not isinstance(transition, Mapping)
            or transition.get("count") != 158
            or not isinstance(shards, Mapping)
            or shards.get("count") != 86
        ):
            raise Phase6ReleaseError("execution v4 policy/cardinality changed")
    elif label == "aggregation_v8":
        policy = payload.get("validation_policy")
        if (
            payload.get("contract_only") is not True
            or payload.get("no_observable_pass_claimed") is not True
            or payload.get("global_green_permitted") is not False
            or payload.get("solver_runs") != 0
            or not isinstance(policy, Mapping)
            or policy.get("aggregate_key_count") != 17818
            or policy.get("shard_count") != 86
        ):
            raise Phase6ReleaseError("aggregation v8 contract-only policy changed")
    elif label == "observable_v2":
        observables = payload.get("observables")
        expected = set(
            GATE_OBSERVABLES["V2"]
            + GATE_OBSERVABLES["V3"]
            + GATE_OBSERVABLES["V4"]
            + GATE_OBSERVABLES["V5"]
        )
        if (
            payload.get("contract_only") is not True
            or payload.get("global_green_permitted") is not False
            or not isinstance(observables, Mapping)
            or set(observables) != expected
        ):
            raise Phase6ReleaseError("observable v2 zero-science policy changed")


def validate_contract_bindings(value: object) -> Mapping[str, object]:
    """Require the exact domain-v3/execution-v4/aggregation-v8/observable-v2 bytes."""

    bindings = _exact(value, set(_CONTRACT_SPECS), "contract bindings")
    for label, spec in _CONTRACT_SPECS.items():
        item = _exact(
            bindings[label],
            {"contract_identity", "manifest_identity"},
            f"contract binding {label}",
        )
        contract = _identity(item["contract_identity"], f"{label} contract")
        manifest = _identity(item["manifest_identity"], f"{label} manifest")
        root = Path(str(spec["root"]))
        if (
            contract["path"] != str(root / str(spec["contract_filename"]))
            or contract["sha256"] != spec["contract_sha256"]
            or manifest["path"] != str(root / "manifest.json")
            or manifest["sha256"] != spec["manifest_sha256"]
        ):
            raise Phase6ReleaseError(f"{label} is not the authoritative frozen root")
        contract_payload = _canonical_json(contract, f"{label} contract")
        manifest_payload = _canonical_json(manifest, f"{label} manifest")
        _validate_contract_payload(label, contract_payload)
        if (
            manifest_payload.get("schema") != spec["schema"]
            or manifest_payload.get("contract") != contract
            or manifest_payload.get("global_green_permitted") is not False
        ):
            raise Phase6ReleaseError(f"{label} manifest is not bound to its contract")
    return bindings


def _validate_scope(value: object, label: str) -> tuple[str, str, str]:
    item = _exact(value, {"domain_id", "gate", "observable"}, label)
    gate = _required_text(item["gate"], f"{label} gate")
    observable = _required_text(item["observable"], f"{label} observable")
    domain_id = _identifier(item["domain_id"], f"{label} domain_id")
    if gate not in GATE_OBSERVABLES or observable not in GATE_OBSERVABLES[gate]:
        raise Phase6ReleaseError(f"{label} gate/observable pair changed")
    return gate, observable, domain_id


def _validate_source_artifact(
    value: object, label: str
) -> tuple[Mapping[str, object], object, str]:
    item = _exact(
        value,
        {"artifact_role", "expected_schema", "identity", "media_type"},
        label,
    )
    media_type = item["media_type"]
    artifact_role = item["artifact_role"]
    if media_type not in MEDIA_TYPES:
        raise Phase6ReleaseError(f"{label} media type changed")
    if artifact_role not in SOURCE_ARTIFACT_ROLES:
        raise Phase6ReleaseError(f"{label} artifact role changed")
    identity = _identity(item["identity"], f"{label} identity")
    if media_type == "application/json":
        schema = _required_text(item["expected_schema"], f"{label} expected schema")
        payload = _canonical_json(identity, label)
        if payload.get("schema", payload.get("schema_version")) != schema:
            raise Phase6ReleaseError(f"{label} expected schema changed")
        return identity, payload, str(artifact_role)
    if media_type == "application/x-jsonlines":
        if item["expected_schema"] is not None:
            raise Phase6ReleaseError(f"{label} JSONL expected schema must be null")
        return identity, _canonical_jsonl(identity, label), str(artifact_role)
    if item["expected_schema"] is not None:
        raise Phase6ReleaseError(f"{label} binary expected schema must be null")
    return identity, None, str(artifact_role)


def _state_like(payload: object) -> str | None:
    if not isinstance(payload, Mapping):
        return None
    for name in (
        "release_evidence_state",
        "scientific_acceptance_status",
        "acceptance_state",
        "overall_state",
        "state",
        "status",
    ):
        value = payload.get(name)
        if value in STATES:
            return str(value)
    return None


def _source_payload_supports_role(
    sources: Sequence[tuple[object, str]],
    *,
    role: str,
    declared_state: str,
    blocker: object,
) -> None:
    json_objects = [
        payload
        for payload, artifact_role in sources
        if artifact_role == "RESULT" and isinstance(payload, Mapping)
    ]
    if not json_objects:
        raise Phase6ReleaseError(
            "evidence envelope lacks a JSON RESULT metadata source"
        )
    for payload in json_objects:
        if payload.get("global_green_permitted", False) is not False:
            raise Phase6ReleaseError("source evidence permits a global GREEN claim")
        for field in (
            "paper_agreement_primary_gate",
            "li_figure_agreement_primary_gate",
            "paper_figure_agreement_primary_gate",
        ):
            if field in payload and payload[field] is not False:
                raise Phase6ReleaseError("source evidence promotes paper agreement")
    if role in {"PRIMARY_SCIENCE", "INDEPENDENT_SCIENCE"}:
        candidates = [
            payload
            for payload in json_objects
            if payload.get("scientific_evidence") is True
            and payload.get("kernel_unit_test_only") is False
            and payload.get("contract_only") is not True
            and payload.get("no_observable_pass_claimed") is not True
        ]
        if not candidates:
            raise Phase6ReleaseError(
                "science envelope lacks non-contract science metadata"
            )
        states = {_state_like(payload) for payload in candidates}
        if declared_state not in states:
            raise Phase6ReleaseError(
                "science envelope state is not supported by source"
            )
    elif role == "BLOCKER":
        code = blocker["code"] if isinstance(blocker, Mapping) else None
        if not any(
            payload.get("science_executed") is False
            and (
                _state_like(payload) == "NOT_ASSESSED"
                or payload.get("blocker") == code
                or payload.get("status") == "NOT_ASSESSED"
            )
            for payload in json_objects
        ):
            raise Phase6ReleaseError(
                "blocker envelope lacks a non-executed source blocker"
            )
    elif role == "CONTRACT_ONLY":
        if not any(
            payload.get("contract_only") is True
            or payload.get("no_observable_pass_claimed") is True
            or (
                payload.get("solver_runs") == 0
                and payload.get("scientific_pass_claimed") is False
            )
            for payload in json_objects
        ):
            raise Phase6ReleaseError("contract-only envelope lacks contract evidence")
    elif role == "FAILURE_DIAGNOSTIC":
        if not any(
            payload.get("failure") is not None
            or str(payload.get("status", "")).startswith("FAIL")
            for payload in json_objects
        ):
            raise Phase6ReleaseError("failure envelope lacks a failure diagnostic")
    elif role == "SECONDARY_PAPER_REGRESSION":
        if not any(
            payload.get("secondary_paper_regression") is True
            and payload.get("paper_agreement_primary_gate") is False
            for payload in json_objects
        ):
            raise Phase6ReleaseError(
                "paper regression lacks explicit secondary metadata"
            )
    elif role == "IMPLEMENTATION_VERIFICATION":
        if not any(
            payload.get("verification_evidence") is True
            and payload.get("verification_state") == declared_state
            for payload in json_objects
        ):
            raise Phase6ReleaseError(
                "implementation envelope lacks matching verification evidence"
            )
    elif role == "POLICY_VERIFICATION":
        if not any(
            (
                payload.get("policy_verification") is True
                or payload.get("verification_evidence") is True
            )
            and payload.get("verification_state") == declared_state
            for payload in json_objects
        ):
            raise Phase6ReleaseError(
                "policy envelope lacks matching verification evidence"
            )
    elif role == "CONVENTION_DEFINITION":
        if not any(
            payload.get("convention_definition") is True for payload in json_objects
        ):
            raise Phase6ReleaseError(
                "convention envelope lacks a convention definition"
            )


def validate_evidence_envelope(
    value: object, *, expected_identity: object | None = None
) -> Mapping[str, object]:
    """Validate one normalized immutable evidence envelope."""

    fields = {
        "schema",
        "evidence_id",
        "role",
        "independence_class",
        "declared_state",
        "scientific_evidence",
        "science_executed",
        "kernel_unit_test_only",
        "blocker",
        "implementation_source_sha256s",
        "scopes",
        "source_artifacts",
        "producer",
        "method",
        "global_green_permitted",
        "li_figure_agreement_primary_gate",
        "full_paper_figure_rerun",
    }
    item = _exact(value, fields, "release evidence envelope")
    _json_value(item, "release evidence envelope")
    if (
        item["schema"] != EVIDENCE_ENVELOPE_SCHEMA
        or item["global_green_permitted"] is not False
        or item["li_figure_agreement_primary_gate"] is not False
        or item["full_paper_figure_rerun"] is not False
    ):
        raise Phase6ReleaseError("release evidence policy changed")
    evidence_id = _identifier(item["evidence_id"], "evidence_id")
    role = item["role"]
    independence = item["independence_class"]
    state = item["declared_state"]
    if role not in EVIDENCE_ROLES or independence not in INDEPENDENCE_CLASSES:
        raise Phase6ReleaseError(f"evidence {evidence_id} role/independence changed")
    if state not in STATES:
        raise Phase6ReleaseError(f"evidence {evidence_id} state changed")
    if any(
        not isinstance(item[field], bool)
        for field in (
            "scientific_evidence",
            "science_executed",
            "kernel_unit_test_only",
        )
    ):
        raise Phase6ReleaseError(f"evidence {evidence_id} boolean claims changed")
    _required_text(item["producer"], f"evidence {evidence_id} producer")
    _required_text(item["method"], f"evidence {evidence_id} method")
    implementation_hashes = item["implementation_source_sha256s"]
    if (
        not isinstance(implementation_hashes, list)
        or implementation_hashes != sorted(set(implementation_hashes))
        or any(
            not isinstance(digest, str) or not _SHA256.fullmatch(digest)
            for digest in implementation_hashes
        )
    ):
        raise Phase6ReleaseError(
            f"evidence {evidence_id} implementation source hashes changed"
        )
    scopes = item["scopes"]
    if not isinstance(scopes, list) or not scopes:
        raise Phase6ReleaseError(f"evidence {evidence_id} has no scope")
    scope_keys = [
        _validate_scope(scope, f"evidence {evidence_id} scope[{index}]")
        for index, scope in enumerate(scopes)
    ]
    if scope_keys != sorted(scope_keys) or len(set(scope_keys)) != len(scope_keys):
        raise Phase6ReleaseError(
            f"evidence {evidence_id} scopes are not ordered unique"
        )
    blocker = item["blocker"]
    if role == "BLOCKER":
        block = _exact(blocker, {"code", "reason"}, f"evidence {evidence_id} blocker")
        if not isinstance(block["code"], str) or not _BLOCKER_CODE.fullmatch(
            block["code"]
        ):
            raise Phase6ReleaseError(
                f"evidence {evidence_id} blocker code is not canonical"
            )
        _required_text(block["reason"], f"evidence {evidence_id} blocker reason")
        if (
            state != "NOT_ASSESSED"
            or item["scientific_evidence"] is not False
            or item["science_executed"] is not False
            or item["kernel_unit_test_only"] is not False
            or independence != "NONE"
        ):
            raise Phase6ReleaseError(
                "runtime/blocker evidence is pretending to be a result"
            )
    elif blocker is not None:
        raise Phase6ReleaseError(
            f"non-blocker evidence {evidence_id} carries a blocker"
        )
    if role in {"PRIMARY_SCIENCE", "INDEPENDENT_SCIENCE"}:
        if (
            state not in {"PARTIAL", "PASS", "FAIL"}
            or item["scientific_evidence"] is not True
            or item["science_executed"] is not True
            or item["kernel_unit_test_only"] is not False
        ):
            raise Phase6ReleaseError(f"science evidence {evidence_id} claim changed")
        if not implementation_hashes:
            raise Phase6ReleaseError(
                f"science evidence {evidence_id} lacks implementation source hashes"
            )
        if role == "PRIMARY_SCIENCE" and independence != "SAME_IMPLEMENTATION":
            raise Phase6ReleaseError("primary science independence is contradictory")
        if role == "INDEPENDENT_SCIENCE" and independence not in {
            "ALGORITHMICALLY_INDEPENDENT",
            "EXTERNAL_SOURCE",
        }:
            raise Phase6ReleaseError("independent science is not independent")
    elif role != "BLOCKER" and independence != "NONE":
        raise Phase6ReleaseError(f"support evidence {evidence_id} claims independence")
    if role not in {"PRIMARY_SCIENCE", "INDEPENDENT_SCIENCE"} and implementation_hashes:
        raise Phase6ReleaseError(
            f"support evidence {evidence_id} carries implementation source hashes"
        )
    if role in {
        "IMPLEMENTATION_VERIFICATION",
        "POLICY_VERIFICATION",
        "CONVENTION_DEFINITION",
        "SECONDARY_PAPER_REGRESSION",
        "CONTRACT_ONLY",
    } and (
        item["scientific_evidence"] is not False
        or item["science_executed"] is not False
    ):
        raise Phase6ReleaseError(f"support evidence {evidence_id} claims science")
    if role == "FAILURE_DIAGNOSTIC" and item["scientific_evidence"] is not False:
        raise Phase6ReleaseError("failure diagnostic claims accepted science")
    if role == "CONTRACT_ONLY" and state != "NOT_ASSESSED":
        raise Phase6ReleaseError("contract-only evidence claims an assessment")
    if role == "FAILURE_DIAGNOSTIC" and state != "FAIL":
        raise Phase6ReleaseError("failure diagnostic does not declare FAIL")
    sources = item["source_artifacts"]
    if not isinstance(sources, list) or not sources:
        raise Phase6ReleaseError(f"evidence {evidence_id} has no source artifacts")
    source_results = [
        _validate_source_artifact(source, f"evidence {evidence_id} source[{index}]")
        for index, source in enumerate(sources)
    ]
    identities = [dict(result[0]) for result in source_results]
    paths = [str(identity["path"]) for identity in identities]
    signatures = [
        (str(identity["sha256"]), int(identity["size"])) for identity in identities
    ]
    if (
        paths != sorted(paths)
        or len(set(paths)) != len(paths)
        or len(set(signatures)) != len(signatures)
    ):
        raise Phase6ReleaseError(
            f"evidence {evidence_id} sources are duplicate/unordered"
        )
    _source_payload_supports_role(
        [(result[1], result[2]) for result in source_results],
        role=str(role),
        declared_state=str(state),
        blocker=blocker,
    )
    result_payloads = [result[1] for result in source_results if result[2] == "RESULT"]
    source_strings: set[str] = set()

    def collect_strings(value: object) -> None:
        if isinstance(value, str):
            source_strings.add(value)
        elif isinstance(value, Mapping):
            for nested in value.values():
                collect_strings(nested)
        elif isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
            for nested in value:
                collect_strings(nested)

    for payload in result_payloads:
        collect_strings(payload)
    if any(digest not in source_strings for digest in implementation_hashes):
        raise Phase6ReleaseError(
            f"evidence {evidence_id} implementation hash is absent from RESULT metadata"
        )
    if expected_identity is not None:
        checked = _identity(
            expected_identity, f"evidence {evidence_id} envelope identity"
        )
        raw = Path(str(checked["path"])).read_bytes()
        if canonical_json_bytes(item) != raw:
            raise Phase6ReleaseError(
                f"evidence {evidence_id} identity/envelope mismatch"
            )
    return item


def load_evidence_inventory(value: object) -> dict[str, dict[str, object]]:
    """Load ordered immutable envelopes and reject duplicate-role laundering."""

    if not isinstance(value, list) or not value:
        raise Phase6ReleaseError("release evidence identity list is empty")
    inventory: dict[str, dict[str, object]] = {}
    envelope_signatures: set[tuple[str, int]] = set()
    source_uses: dict[tuple[str, int], set[str]] = {}
    prior_id: str | None = None
    for index, identity_value in enumerate(value):
        identity = _identity(identity_value, f"evidence envelope identity[{index}]")
        signature = (str(identity["sha256"]), int(identity["size"]))
        if signature in envelope_signatures:
            raise Phase6ReleaseError("duplicate evidence envelope bytes")
        envelope_signatures.add(signature)
        envelope = _canonical_json(identity, f"evidence envelope[{index}]")
        validate_evidence_envelope(envelope, expected_identity=identity)
        evidence_id = str(envelope["evidence_id"])
        if prior_id is not None and evidence_id <= prior_id:
            raise Phase6ReleaseError("evidence envelopes are not in evidence_id order")
        prior_id = evidence_id
        if evidence_id in inventory:
            raise Phase6ReleaseError("duplicate evidence_id")
        for source in envelope["source_artifacts"]:
            source_identity = source["identity"]
            source_signature = (
                str(source_identity["sha256"]),
                int(source_identity["size"]),
            )
            artifact_role = str(source["artifact_role"])
            prior_roles = source_uses.setdefault(source_signature, set())
            if artifact_role == "RESULT" or "RESULT" in prior_roles:
                if prior_roles:
                    raise Phase6ReleaseError(
                        "RESULT source evidence is duplicated across envelopes"
                    )
            prior_roles.add(artifact_role)
        inventory[evidence_id] = {
            "identity": dict(identity),
            "envelope": dict(envelope),
        }
    return inventory


def _validate_domain(value: object, label: str) -> Mapping[str, object]:
    item = _exact(
        value,
        {"coverage", "description", "domain_id", "parameters", "selection_policy"},
        label,
    )
    _identifier(item["domain_id"], f"{label} domain_id")
    _required_text(item["description"], f"{label} description")
    _required_text(item["selection_policy"], f"{label} selection policy")
    parameters = item["parameters"]
    if not isinstance(parameters, Mapping) or not parameters:
        raise Phase6ReleaseError(f"{label} parameters must be explicit")
    _json_value(parameters, f"{label} parameters")
    coverage = _exact(
        item["coverage"],
        {"assessed_items", "complete", "expected_items"},
        f"{label} coverage",
    )
    expected = coverage["expected_items"]
    assessed = coverage["assessed_items"]
    if (
        isinstance(expected, bool)
        or not isinstance(expected, int)
        or expected < 1
        or isinstance(assessed, bool)
        or not isinstance(assessed, int)
        or assessed < 0
        or assessed > expected
        or not isinstance(coverage["complete"], bool)
        or coverage["complete"] != (assessed == expected)
    ):
        raise Phase6ReleaseError(f"{label} coverage is contradictory")
    return item


def _validate_assessment(
    value: object,
    label: str,
    *,
    certificate_evidence: set[str],
    inventory: Mapping[str, Mapping[str, object]],
) -> Mapping[str, object]:
    item = _exact(
        value,
        {"applicability", "estimate", "evidence_ids", "reason", "state", "units"},
        label,
    )
    applicability = item["applicability"]
    state = item["state"]
    evidence_ids = item["evidence_ids"]
    if applicability not in {"REQUIRED", "NOT_APPLICABLE"} or state not in STATES:
        raise Phase6ReleaseError(f"{label} applicability/state changed")
    _required_text(item["reason"], f"{label} reason")
    if not isinstance(evidence_ids, list) or evidence_ids != sorted(set(evidence_ids)):
        raise Phase6ReleaseError(f"{label} evidence ids are not ordered unique")
    if any(evidence_id not in certificate_evidence for evidence_id in evidence_ids):
        raise Phase6ReleaseError(f"{label} cites evidence outside its certificate")
    if any(evidence_id not in inventory for evidence_id in evidence_ids):
        raise Phase6ReleaseError(f"{label} cites missing evidence")
    estimate = item["estimate"]
    units = item["units"]
    if applicability == "NOT_APPLICABLE":
        if (
            state != "NOT_ASSESSED"
            or estimate is not None
            or units is not None
            or evidence_ids
        ):
            raise Phase6ReleaseError(f"{label} NOT_APPLICABLE record is contradictory")
    else:
        _required_text(units, f"{label} units")
        if state in {"PASS", "FAIL"}:
            _decimal(estimate, f"{label} estimate")
            if not evidence_ids:
                raise Phase6ReleaseError(f"{label} assessed state lacks evidence")
        elif estimate is not None:
            _decimal(estimate, f"{label} estimate")
        for evidence_id in evidence_ids:
            envelope = inventory[evidence_id]["envelope"]
            role = envelope["role"]
            if role == "SECONDARY_PAPER_REGRESSION" or (
                state == "PASS" and role in {"BLOCKER", "CONTRACT_ONLY"}
            ):
                raise Phase6ReleaseError(f"{label} is promoted by invalid evidence")
            if state == "PASS" and envelope["declared_state"] != "PASS":
                raise Phase6ReleaseError(
                    f"{label} PASS is supported by non-PASS evidence"
                )
        if (
            state == "FAIL"
            and evidence_ids
            and not any(
                inventory[evidence_id]["envelope"]["declared_state"] == "FAIL"
                for evidence_id in evidence_ids
            )
        ):
            raise Phase6ReleaseError(f"{label} FAIL lacks FAIL evidence")
    return item


def _validate_budget(
    value: object,
    label: str,
    *,
    fields: Sequence[str],
    certificate_evidence: set[str],
    inventory: Mapping[str, Mapping[str, object]],
) -> Mapping[str, object]:
    budget = _exact(value, set(fields), label)
    for field in fields:
        _validate_assessment(
            budget[field],
            f"{label}.{field}",
            certificate_evidence=certificate_evidence,
            inventory=inventory,
        )
    return budget


def _evidence_supports_scope(
    envelope: Mapping[str, object], scope: tuple[str, str, str]
) -> bool:
    return any(
        _validate_scope(item, "evidence scope") == scope for item in envelope["scopes"]
    )


def validate_certificate(
    value: object,
    *,
    inventory: Mapping[str, Mapping[str, object]],
) -> Mapping[str, object]:
    """Validate one per-observable/per-domain certificate."""

    fields = {
        "schema",
        "certificate_id",
        "gate",
        "observable",
        "parameter_domain",
        "state",
        "reason",
        "primary_acceptance_gate",
        "evidence_ids",
        "numerical_uncertainty_budget",
        "convention_uncertainty_budget",
        "limitations",
        "blocker",
    }
    item = _exact(value, fields, "release certificate")
    if item["schema"] != CERTIFICATE_SCHEMA:
        raise Phase6ReleaseError("release certificate schema changed")
    certificate_id = _identifier(item["certificate_id"], "certificate_id")
    gate = _required_text(item["gate"], f"certificate {certificate_id} gate")
    observable = _required_text(
        item["observable"], f"certificate {certificate_id} observable"
    )
    if gate not in GATE_OBSERVABLES or observable not in GATE_OBSERVABLES[gate]:
        raise Phase6ReleaseError(
            f"certificate {certificate_id} gate/observable changed"
        )
    domain = _validate_domain(
        item["parameter_domain"], f"certificate {certificate_id} domain"
    )
    scope = (gate, observable, str(domain["domain_id"]))
    state = item["state"]
    if state not in STATES:
        raise Phase6ReleaseError(f"certificate {certificate_id} state changed")
    reason = _required_text(item["reason"], f"certificate {certificate_id} reason")
    if has_forbidden_global_claim(reason):
        raise Phase6ReleaseError(f"certificate {certificate_id} claims a global result")
    primary_gate = _required_text(
        item["primary_acceptance_gate"],
        f"certificate {certificate_id} primary acceptance gate",
    )
    if _FORBIDDEN_PRIMARY.search(primary_gate):
        raise Phase6ReleaseError("Li/paper/raster agreement cannot be a primary gate")
    evidence_ids = item["evidence_ids"]
    if (
        not isinstance(evidence_ids, list)
        or not evidence_ids
        or evidence_ids != sorted(set(evidence_ids))
    ):
        raise Phase6ReleaseError(
            f"certificate {certificate_id} evidence is missing/duplicate"
        )
    if any(evidence_id not in inventory for evidence_id in evidence_ids):
        raise Phase6ReleaseError(f"certificate {certificate_id} cites missing evidence")
    for evidence_id in evidence_ids:
        envelope = inventory[evidence_id]["envelope"]
        if not _evidence_supports_scope(envelope, scope):
            raise Phase6ReleaseError(
                f"evidence {evidence_id} does not cover certificate {certificate_id}"
            )
    evidence_set = set(evidence_ids)
    numerical = _validate_budget(
        item["numerical_uncertainty_budget"],
        f"certificate {certificate_id} numerical budget",
        fields=NUMERICAL_BUDGET_FIELDS,
        certificate_evidence=evidence_set,
        inventory=inventory,
    )
    convention = _validate_budget(
        item["convention_uncertainty_budget"],
        f"certificate {certificate_id} convention budget",
        fields=CONVENTION_BUDGET_FIELDS,
        certificate_evidence=evidence_set,
        inventory=inventory,
    )
    limitations = item["limitations"]
    if not isinstance(limitations, list) or any(
        not isinstance(text, str) or not text.strip() for text in limitations
    ):
        raise Phase6ReleaseError(f"certificate {certificate_id} limitations changed")
    if any(has_forbidden_global_claim(text) for text in limitations):
        raise Phase6ReleaseError(
            f"certificate {certificate_id} limitation claims global status"
        )
    roles = {
        str(inventory[evidence_id]["envelope"]["role"]) for evidence_id in evidence_ids
    }
    driving_roles = {
        "PRIMARY_SCIENCE",
        "INDEPENDENT_SCIENCE",
        "IMPLEMENTATION_VERIFICATION",
        "POLICY_VERIFICATION",
        "FAILURE_DIAGNOSTIC",
    }
    driving_states = [
        str(inventory[evidence_id]["envelope"]["declared_state"])
        for evidence_id in evidence_ids
        if inventory[evidence_id]["envelope"]["role"] in driving_roles
    ]
    if gate in PHYSICAL_GATES:
        if any(
            assessment["applicability"] != "REQUIRED"
            for budget in (numerical, convention)
            for assessment in budget.values()
        ):
            raise Phase6ReleaseError(
                f"physical certificate {certificate_id} omits an uncertainty component"
            )
    else:
        if any(
            assessment["applicability"] != "NOT_APPLICABLE"
            for budget in (numerical, convention)
            for assessment in budget.values()
        ):
            raise Phase6ReleaseError(
                f"policy certificate {certificate_id} must mark physical budgets N/A"
            )
    coverage = domain["coverage"]
    blocker = item["blocker"]
    if state == "PASS":
        if coverage["complete"] is not True or blocker is not None:
            raise Phase6ReleaseError(
                f"PASS certificate {certificate_id} is incomplete/blocked"
            )
        required_assessments = [
            assessment
            for budget in (numerical, convention)
            for assessment in budget.values()
            if assessment["applicability"] == "REQUIRED"
        ]
        if any(assessment["state"] != "PASS" for assessment in required_assessments):
            raise Phase6ReleaseError(
                f"PASS certificate {certificate_id} has an open budget"
            )
        if roles & {"BLOCKER", "CONTRACT_ONLY"}:
            raise Phase6ReleaseError(
                "blocked/contract-only evidence cannot promote PASS"
            )
        if not driving_states or any(
            state_value != "PASS" for state_value in driving_states
        ):
            raise Phase6ReleaseError(
                f"PASS certificate {certificate_id} is not derived from PASS evidence"
            )
        if (
            gate in PHYSICAL_GATES
            and not {
                "PRIMARY_SCIENCE",
                "INDEPENDENT_SCIENCE",
            }
            <= roles
        ):
            raise Phase6ReleaseError(
                f"physical PASS {certificate_id} lacks primary and independent science"
            )
        if gate in PHYSICAL_GATES:
            primary_sources = {
                digest
                for evidence_id in evidence_ids
                if inventory[evidence_id]["envelope"]["role"] == "PRIMARY_SCIENCE"
                for digest in inventory[evidence_id]["envelope"][
                    "implementation_source_sha256s"
                ]
            }
            independent_sources = {
                digest
                for evidence_id in evidence_ids
                if inventory[evidence_id]["envelope"]["role"] == "INDEPENDENT_SCIENCE"
                for digest in inventory[evidence_id]["envelope"][
                    "implementation_source_sha256s"
                ]
            }
            if primary_sources & independent_sources:
                raise Phase6ReleaseError(
                    f"physical PASS {certificate_id} reuses an implementation source"
                )
        if gate == "V0" and "IMPLEMENTATION_VERIFICATION" not in roles:
            raise Phase6ReleaseError("V0 PASS lacks implementation verification")
        if gate == "V6" and "POLICY_VERIFICATION" not in roles:
            raise Phase6ReleaseError("V6 PASS lacks policy verification")
    elif state == "NOT_ASSESSED":
        block = _exact(
            blocker, {"code", "reason"}, f"certificate {certificate_id} blocker"
        )
        if not isinstance(block["code"], str) or not _BLOCKER_CODE.fullmatch(
            block["code"]
        ):
            raise Phase6ReleaseError(
                f"certificate {certificate_id} blocker code is not canonical"
            )
        _required_text(block["reason"], f"certificate {certificate_id} blocker reason")
        if coverage["assessed_items"] != 0 or roles - {"BLOCKER", "CONTRACT_ONLY"}:
            raise Phase6ReleaseError(
                f"NOT_ASSESSED certificate {certificate_id} contains result evidence"
            )
        if "BLOCKER" not in roles:
            raise Phase6ReleaseError(
                f"NOT_ASSESSED certificate {certificate_id} lacks blocker evidence"
            )
        if any(
            inventory[evidence_id]["envelope"]["role"] == "BLOCKER"
            and inventory[evidence_id]["envelope"]["blocker"] != block
            for evidence_id in evidence_ids
        ):
            raise Phase6ReleaseError(
                f"certificate {certificate_id} blocker does not match its evidence"
            )
    elif blocker is not None:
        raise Phase6ReleaseError(
            f"assessed certificate {certificate_id} carries a blocker"
        )
    if state == "PARTIAL" and not roles & {
        "PRIMARY_SCIENCE",
        "INDEPENDENT_SCIENCE",
        "IMPLEMENTATION_VERIFICATION",
        "POLICY_VERIFICATION",
        "FAILURE_DIAGNOSTIC",
    }:
        raise Phase6ReleaseError(
            f"PARTIAL certificate {certificate_id} lacks measured evidence"
        )
    if state == "PARTIAL" and "FAIL" in driving_states:
        raise Phase6ReleaseError(
            f"PARTIAL certificate {certificate_id} hides FAIL evidence"
        )
    if state == "FAIL" and not roles & {
        "PRIMARY_SCIENCE",
        "INDEPENDENT_SCIENCE",
        "FAILURE_DIAGNOSTIC",
        "IMPLEMENTATION_VERIFICATION",
        "POLICY_VERIFICATION",
    }:
        raise Phase6ReleaseError(
            f"FAIL certificate {certificate_id} lacks failure evidence"
        )
    if state == "FAIL" and "FAIL" not in driving_states:
        raise Phase6ReleaseError(
            f"FAIL certificate {certificate_id} is not derived from FAIL evidence"
        )
    return item


def _validate_policy(value: object) -> Mapping[str, object]:
    fields = {
        "acceptance_is_per_observable_and_domain",
        "full_paper_figure_rerun_performed",
        "global_green_permitted",
        "li_figure_agreement_primary_gate",
        "publisher_generated_science",
    }
    policy = _exact(value, fields, "release policy")
    if (
        policy["acceptance_is_per_observable_and_domain"] is not True
        or policy["full_paper_figure_rerun_performed"] is not False
        or policy["global_green_permitted"] is not False
        or policy["li_figure_agreement_primary_gate"] is not False
        or policy["publisher_generated_science"] is not False
    ):
        raise Phase6ReleaseError("release policy changed")
    return policy


def validate_submission(
    value: object,
) -> tuple[dict[str, dict[str, object]], tuple[Mapping[str, object], ...]]:
    """Validate a canonical release submission without publishing anything."""

    fields = {
        "schema",
        "release_id",
        "contract_bindings",
        "evidence_envelope_identities",
        "certificates",
        "policy",
    }
    item = _exact(value, fields, "release submission")
    if item["schema"] != SUBMISSION_SCHEMA:
        raise Phase6ReleaseError("release submission schema changed")
    _identifier(item["release_id"], "release_id")
    validate_contract_bindings(item["contract_bindings"])
    _validate_policy(item["policy"])
    inventory = load_evidence_inventory(item["evidence_envelope_identities"])
    certificates_value = item["certificates"]
    if not isinstance(certificates_value, list) or not certificates_value:
        raise Phase6ReleaseError("release certificate list is empty")
    certificates = tuple(
        validate_certificate(certificate, inventory=inventory)
        for certificate in certificates_value
    )
    ids = [str(certificate["certificate_id"]) for certificate in certificates]
    if ids != sorted(ids) or len(set(ids)) != len(ids):
        raise Phase6ReleaseError("certificates are not in certificate_id order")
    scopes = [
        (
            str(certificate["gate"]),
            str(certificate["observable"]),
            str(certificate["parameter_domain"]["domain_id"]),
        )
        for certificate in certificates
    ]
    if len(set(scopes)) != len(scopes):
        raise Phase6ReleaseError("duplicate certificate observable/domain scope")
    present = {(scope[0], scope[1]) for scope in scopes}
    missing = sorted(REQUIRED_LEDGER_SLICES - present)
    if missing:
        raise Phase6ReleaseError(
            f"release ledger omits required gate slices: {missing}"
        )
    return inventory, certificates


def build_ledger(value: object, *, submission_sha256: str) -> dict[str, object]:
    """Build the deterministic ledger derived from a validated submission."""

    if not _SHA256.fullmatch(submission_sha256):
        raise Phase6ReleaseError("submission_sha256 is invalid")
    item = dict(
        _exact(
            value,
            {
                "schema",
                "release_id",
                "contract_bindings",
                "evidence_envelope_identities",
                "certificates",
                "policy",
            },
            "release submission",
        )
    )
    inventory, certificates = validate_submission(item)
    states = Counter(str(certificate["state"]) for certificate in certificates)
    gates = Counter(str(certificate["gate"]) for certificate in certificates)
    ledger = {
        "schema": LEDGER_SCHEMA,
        "release_id": item["release_id"],
        "submission_sha256": submission_sha256,
        "contract_bindings": item["contract_bindings"],
        "evidence_inventory": {
            evidence_id: record for evidence_id, record in sorted(inventory.items())
        },
        "certificates": [dict(certificate) for certificate in certificates],
        "certificate_count": len(certificates),
        "state_counts": {state: states[state] for state in STATES},
        "gate_certificate_counts": {gate: gates[gate] for gate in GATES},
        "pass_certificate_count": states["PASS"],
        "policy": dict(item["policy"]),
        "global_status": None,
    }
    validate_ledger(ledger)
    return ledger


def validate_ledger(value: object) -> Mapping[str, object]:
    """Reload and validate a published ledger, including every live identity."""

    fields = {
        "schema",
        "release_id",
        "submission_sha256",
        "contract_bindings",
        "evidence_inventory",
        "certificates",
        "certificate_count",
        "state_counts",
        "gate_certificate_counts",
        "pass_certificate_count",
        "policy",
        "global_status",
    }
    item = _exact(value, fields, "release ledger")
    if item["schema"] != LEDGER_SCHEMA or item["global_status"] is not None:
        raise Phase6ReleaseError("release ledger claims a global status")
    _identifier(item["release_id"], "release ledger release_id")
    if not isinstance(item["submission_sha256"], str) or not _SHA256.fullmatch(
        item["submission_sha256"]
    ):
        raise Phase6ReleaseError("release ledger submission hash changed")
    validate_contract_bindings(item["contract_bindings"])
    _validate_policy(item["policy"])
    inventory_value = item["evidence_inventory"]
    if not isinstance(inventory_value, Mapping) or not inventory_value:
        raise Phase6ReleaseError("release ledger evidence inventory is empty")
    if list(inventory_value) != sorted(inventory_value):
        raise Phase6ReleaseError("release ledger evidence inventory order changed")
    identities: list[object] = []
    for evidence_id, record in inventory_value.items():
        if not isinstance(evidence_id, str):
            raise Phase6ReleaseError("release ledger evidence id changed")
        entry = _exact(
            record, {"envelope", "identity"}, f"ledger evidence {evidence_id}"
        )
        identities.append(entry["identity"])
    inventory = load_evidence_inventory(identities)
    if set(inventory) != set(inventory_value):
        raise Phase6ReleaseError("release ledger evidence inventory keys changed")
    for evidence_id, record in inventory_value.items():
        if record != inventory[evidence_id]:
            raise Phase6ReleaseError("release ledger embedded envelope changed")
    certificates_value = item["certificates"]
    if not isinstance(certificates_value, list):
        raise Phase6ReleaseError("release ledger certificate list changed")
    certificates = tuple(
        validate_certificate(certificate, inventory=inventory)
        for certificate in certificates_value
    )
    ids = [str(certificate["certificate_id"]) for certificate in certificates]
    scopes = [
        (
            str(certificate["gate"]),
            str(certificate["observable"]),
            str(certificate["parameter_domain"]["domain_id"]),
        )
        for certificate in certificates
    ]
    if (
        ids != sorted(ids)
        or len(set(ids)) != len(ids)
        or len(set(scopes)) != len(scopes)
    ):
        raise Phase6ReleaseError("release ledger certificate order/scope changed")
    if REQUIRED_LEDGER_SLICES - {(scope[0], scope[1]) for scope in scopes}:
        raise Phase6ReleaseError("release ledger required gate slice disappeared")
    states = Counter(str(certificate["state"]) for certificate in certificates)
    gates = Counter(str(certificate["gate"]) for certificate in certificates)
    expected_state_counts = {state: states[state] for state in STATES}
    expected_gate_counts = {gate: gates[gate] for gate in GATES}
    if (
        item["certificate_count"] != len(certificates)
        or item["state_counts"] != expected_state_counts
        or item["gate_certificate_counts"] != expected_gate_counts
        or item["pass_certificate_count"] != states["PASS"]
    ):
        raise Phase6ReleaseError("release ledger counts are not derived")
    return item


__all__ = [
    "CERTIFICATE_SCHEMA",
    "CONVENTION_BUDGET_FIELDS",
    "EVIDENCE_ENVELOPE_SCHEMA",
    "EVIDENCE_ROLES",
    "GATES",
    "GATE_OBSERVABLES",
    "has_forbidden_global_claim",
    "LEDGER_SCHEMA",
    "MANIFEST_SCHEMA",
    "NUMERICAL_BUDGET_FIELDS",
    "Phase6ReleaseError",
    "REQUIRED_LEDGER_SLICES",
    "SOURCE_ARTIFACT_ROLES",
    "STATES",
    "SUBMISSION_SCHEMA",
    "authoritative_contract_bindings",
    "build_ledger",
    "direct_file_identity",
    "load_evidence_inventory",
    "sha256_bytes",
    "validate_certificate",
    "validate_contract_bindings",
    "validate_evidence_envelope",
    "validate_ledger",
    "validate_submission",
]
